import type { ControlSettingsBySlug, ControlSlug } from "./types";

const baseFieldDefaults = {
  mode: "stacked" as const,
  labelPosition: "left" as const,
  errorEnabled: false,
  error: "This field is required",
  helpEnabled: false,
  help: "Optional help text for this field",
  required: false,
};

export const defaultSettings: ControlSettingsBySlug = {
  button: {
    variant: "primary",
    label: "Button",
    disabled: false,
  },
  "submit-button": {
    variant: "primary",
    label: "Submit",
    disabled: false,
  },
  "reset-button": {
    variant: "secondary",
    label: "Reset",
    disabled: false,
  },
  checkbox: {
    ...baseFieldDefaults,
    label: "I agree to the Terms & Conditions",
    mode: "flagged",
    labelPosition: "right",
    checked: false,
    shape: "square",
  },
  switch: {
    ...baseFieldDefaults,
    label: "Enable notifications",
    mode: "flagged",
    labelPosition: "right",
    checked: true,
  },
  "radio-group": {
    ...baseFieldDefaults,
    label: "Account type",
    value: "personal",
    shape: "round",
    error: "Please select an account type",
    optionErrorsEnabled: false,
    optionError: "This option needs review",
  },
  "color-picker": {
    ...baseFieldDefaults,
    label: "Choose a colour",
    value: "#6D2BD9",
  },
  "date-picker": {
    ...baseFieldDefaults,
    label: "Date of birth",
    value: "1990-05-24",
  },
  "time-picker": {
    ...baseFieldDefaults,
    label: "Start time",
    value: "09:30",
  },
  "datetime-picker": {
    ...baseFieldDefaults,
    label: "Appointment",
    value: "1990-05-24T09:30",
  },
  "month-picker": {
    ...baseFieldDefaults,
    label: "Billing month",
    value: "1990-05",
  },
  "week-picker": {
    ...baseFieldDefaults,
    label: "Planning week",
    value: "1990-W21",
  },
  "email-input": {
    ...baseFieldDefaults,
    label: "Email address",
    value: "jane.cooper@example.com",
  },
  "telephone-input": {
    ...baseFieldDefaults,
    label: "Phone number",
    value: "+44 7700 900123",
  },
  "url-input": {
    ...baseFieldDefaults,
    label: "Website",
    value: "https://example.com",
  },
  "search-input": {
    ...baseFieldDefaults,
    label: "Search",
    value: "Search query",
  },
  "file-upload": {
    ...baseFieldDefaults,
    label: "Upload a file",
    fileName: "",
  },
  "hidden-input": {
    ...baseFieldDefaults,
    label: "Campaign ID",
    name: "campaignId",
    value: "campaign-id-42",
    helpEnabled: true,
    help: "Hidden fields are not visible to users but submit with the form.",
  },
  "number-input": {
    ...baseFieldDefaults,
    label: "Quantity",
    value: 3,
    min: 1,
    max: 100,
    step: 1,
  },
  "password-input": {
    ...baseFieldDefaults,
    label: "Password",
    value: "hunter2!",
  },
  "range-slider": {
    ...baseFieldDefaults,
    label: "Volume",
    value: 60,
    min: 0,
    max: 100,
    step: 1,
  },
  select: {
    ...baseFieldDefaults,
    label: "Country",
    value: "Select a country",
    options: "Select a country, United Kingdom, United States, Canada",
  },
  "text-input": {
    ...baseFieldDefaults,
    label: "Full name",
    value: "Jane Cooper",
    placeholder: "Enter your full name",
    placeholderEnabled: false,
  },
  textarea: {
    ...baseFieldDefaults,
    label: "Your message",
    value: "",
    maxCharsEnabled: true,
    maxChars: 500,
    placeholder: "Type your message here...",
    placeholderEnabled: true,
  },
  "theme-toggle": {
    mode: "flagged",
    labelPosition: "left",
    label: "Theme",
    value: "dark",
  },
  tooltip: {
    content: "Optional help text for this field",
    demoLabel: "Field label",
  },
  dialog: {
    actionSet: "ok-cancel",
    status: "success",
    title: "Ready to continue",
    description: "Everything looks good. Confirm to move forward.",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    open: false,
  },
  drawer: {
    title: "Filters",
    description: "Refine the current view without leaving the page.",
    content:
      "Drawers are useful for secondary workflows, navigation, filters, inspector panels, and compact forms that should stay connected to the current screen.",
    contentType: "html",
    side: "right",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeButton: true,
    footerActions: true,
    open: false,
  },
  "dropdown-menu": {
    placement: "bottom-start",
    closeOnSelect: true,
    closeOnOutside: true,
    closeOnEscape: true,
    showIcons: true,
    showDestructive: true,
    showDisabled: true,
    open: false,
  },
  "context-menu": {
    closeOnSelect: true,
    closeOnOutside: true,
    closeOnEscape: true,
    showIcons: true,
    showDestructive: true,
    showDisabled: true,
    open: false,
    targetLabel: "Right-click this area",
  },
  "command-palette": {
    open: false,
    placeholder: "Search commands…",
    emptyMessage: "No commands found.",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeOnSelect: true,
    showShortcuts: true,
    showDescriptions: true,
    showGroups: true,
    showEmptyResults: false,
  },
  modal: {
    title: "Project details",
    description: "Review supporting information without leaving the page.",
    content:
      "Modals are useful for focused workflows, longer explanatory content, previews, and forms that need more room than a confirmation dialog.",
    contentType: "html",
    size: "medium",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeButton: true,
    footerActions: true,
    open: false,
  },
  popover: {
    title: "Quick actions",
    content:
      "Popovers are useful for compact contextual panels, inline settings, preview cards, and lightweight forms anchored to a trigger.",
    contentType: "html",
    placement: "bottom",
    closeOnOutside: true,
    closeOnEscape: true,
    showArrow: true,
    open: false,
  },
  "alert": {
    status: "error",
    title: "There was a problem with your submission.",
    description: "Please correct the errors below and try again.",
    dismissible: true,
    iconFlagged: true,
    visible: true,
  },
  toast: {
    status: "success",
    title: "Changes saved",
    description: "Your profile was updated successfully.",
    descriptionEnabled: true,
    dismissible: true,
    autoDismissEnabled: true,
    positionVertical: "top",
    positionHorizontal: "right",
  },
  tabs: {
    activeValue: "overview",
    disabledSecond: false,
    fitted: false,
    orientation: "horizontal",
    variant: "line",
  },
  card: {
    title: "Component health",
    eyebrow: "Library status",
    content:
      "Cards are compact content containers for summaries, previews, metrics, and calls to action.",
    tone: "accent",
    density: "comfortable",
    media: true,
    footerActions: true,
  },
  panel: {
    title: "Release readiness",
    description: "A structural panel for settings, grouped content, and page sections.",
    content:
      "Panels are broader layout primitives than cards. Use them for page sections, settings groups, and structured content blocks.",
    tone: "default",
    density: "comfortable",
    divided: true,
    footer: "Panel footer content can hold metadata, hints, or actions.",
  },
  section: {
    title: "Page layout",
    description: "Responsive rows and columns that stack on mobile and expand on larger screens.",
    sidebar: "none",
    columns: 3,
    gap: "md",
    stackBelow: "mobile",
    sidebarRatio: "1:2",
    sidebarTitle: "Sidebar",
    sidebarContent: "Navigation, filters, or supporting controls beside the main content area.",
    columnOneTitle: "Primary column",
    columnOneContent: "Main content area. On mobile this stacks above the secondary column.",
    columnTwoTitle: "Secondary column",
    columnTwoContent: "Supporting content beside the primary column.",
    columnThreeTitle: "Third column",
    columnThreeContent: "Additional equal-width content column on desktop.",
    columnFourTitle: "Fourth column",
    columnFourContent: "Fourth equal column on wider desktop layouts.",
    columnFiveTitle: "Fifth column",
    columnFiveContent: "Fifth equal column on wider desktop layouts.",
  },
  table: {
    caption: "Component adoption by team",
    density: "comfortable",
    striped: true,
    bordered: false,
    showCaption: true,
    showEmpty: false,
    numericColumn: true,
  },
  "data-grid": {
    caption: "Quarterly component metrics",
    density: "compact",
    striped: true,
    bordered: true,
    filterable: true,
    resizable: true,
    rowHeaderResizable: false,
    q1Q2Resizable: true,
    q1Q2SortFilter: false,
    sortable: true,
    stickyHeader: true,
    stickyFirstColumn: true,
    numericColumns: true,
  },
  skeleton: {
    animation: "shimmer",
    lines: 3,
    variant: "card",
  },
  carousel: {
    initialIndex: 0,
    loop: true,
    showCaptions: true,
    showPips: true,
  },
  lightbox: {
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    showCaptions: true,
    triggerLabel: "Open lightbox",
  },
  "image-thumbnail": {
    openInLightbox: true,
    showCaption: true,
    size: "medium",
  },
  "image-gallery": {
    columns: 4,
    showCaptions: true,
    thumbnailSize: "small",
  },
  "model-viewer": {
    autoRotate: true,
    cameraControls: true,
    showCaption: true,
  },
  "model-lightbox": {
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    showCaption: true,
    triggerLabel: "Open 3D asset",
  },
  "model-thumbnail": {
    openInLightbox: true,
    showCaption: true,
    size: "medium",
  },
  "model-gallery": {
    columns: 4,
    showCaptions: true,
    thumbnailSize: "small",
  },
  accordion: {
    title: "What is included?",
    content:
      "Every plan includes unlimited projects, shared workspaces, and priority email support during business hours.",
    defaultOpen: false,
    disabled: false,
  },
  "accordion-group": {
    type: "single",
    collapsible: true,
    defaultOpenFirst: true,
    itemOneTitle: "Getting started",
    itemOneContent:
      "Create a workspace, invite your team, and import existing content from Markdown or HTML.",
    itemTwoTitle: "Billing & plans",
    itemTwoContent:
      "Upgrade or downgrade at any time. Invoices are emailed on the first of each month.",
    itemThreeTitle: "Support",
    itemThreeContent:
      "Reach us through in-app chat or email support@example.com. Enterprise customers get a dedicated channel.",
  },
  "show-more": {
    content:
      "Every plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.",
    maxLines: 3,
    showMoreLabel: "Show more",
    showLessLabel: "Show less",
    defaultExpanded: false,
  },
  "empty-state": {
    title: "No components yet",
    description: "Create your first component to start building your library and sharing patterns across teams.",
    density: "comfortable",
    showIcon: true,
    icon: "inbox",
    primaryAction: true,
    primaryActionLabel: "Create component",
    secondaryAction: true,
    secondaryActionLabel: "Browse templates",
  },
  sidebar: {
    side: "left",
    collapsed: false,
    density: "comfortable",
    showHeader: true,
    headerTitle: "Opus",
    showFooter: true,
    footerText: "Signed in as Alex Morgan",
    activeItem: "library",
    groupOpen: true,
  },
  "mega-menu": {
    closeOnEscape: true,
    closeOnOutside: true,
    density: "comfortable",
    featured: true,
  },
  "top-navigation": {
    activeMenu: "none",
    closeOnEscape: true,
    closeOnOutside: true,
    closeOnSelect: true,
    density: "comfortable",
    showShortcuts: true,
  },
};

export function getDefaultSettings<S extends ControlSlug>(slug: S): ControlSettingsBySlug[S] {
  return structuredClone(defaultSettings[slug]);
}
