import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAlignLeft,
  faBars,
  faBullseye,
  faChartColumn,
  faBell,
  faCalendar,
  faCalendarDays,
  faCalendarWeek,
  faCaretDown,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faChevronRight,
  faCircleDot,
  faCircleInfo,
  faCircleUser,
  faClipboardList,
  faClone,
  faCloudArrowUp,
  faClock,
  faClockRotateLeft,
  faCode,
  faCodeBranch,
  faColumns,
  faComments,
  faBorderAll,
  faCopy,
  faCube,
  faDoorOpen,
  faEllipsis,
  faEnvelope,
  faExpand,
  faExpandAlt,
  faEye,
  faEyeSlash,
  faFaceSmile,
  faFilter,
  faFlask,
  faFont,
  faGears,
  faGavel,
  faGlobe,
  faGrip,
  faGripLines,
  faGripLinesVertical,
  faHeading,
  faIcons,
  faHashtag,
  faIdCard,
  faImage,
  faInbox,
  faKeyboard,
  faLayerGroup,
  faLink,
  faList,
  faListCheck,
  faLock,
  faMagnifyingGlass,
  faMaximize,
  faMessage,
  faMinus,
  faMobileScreen,
  faMoon,
  faMousePointer,
  faNoteSticky,
  faObjectGroup,
  faPalette,
  faPaperPlane,
  faPenToSquare,
  faPhone,
  faPlay,
  faPlus,
  faPager,
  faRotateLeft,
  faRightLeft,
  faSitemap,
  faSliders,
  faSpinner,
  faSquare,
  faSquareCheck,
  faStar,
  faSun,
  faTable,
  faTableCells,
  faTableColumns,
  faTags,
  faTerminal,
  faTimeline,
  faToggleOn,
  faTrophy,
  faTriangleExclamation,
  faUpRightAndDownLeftFromCenter,
  faUserShield,
  faUsers,
  faVideo,
  faWindowMaximize,
  faWindowRestore,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";
import type { ComponentCategory, ControlSlug } from "./types";

const componentIcons: Record<string, IconDefinition> = {
  accordion: faList,
  "accordion-group": faLayerGroup,
  button: faSquare,
  card: faClone,
  "kpi-card": faChartColumn,
  "stat-card": faUsers,
  "gauge": faBullseye,
  "pipeline-overview": faFilter,
  "deals-over-time": faChartLine,
  "upcoming-tasks": faListCheck,
  "recent-activity": faClockRotateLeft,
  "top-performing-users": faTrophy,
  "user-profile": faCircleUser,
  "profile-photo-upload": faCircleUser,
  "dashboard-content-container": faBorderAll,
  "dashboard-list-columns": faTableColumns,
  "notes-activity": faComments,
  "lab-dashboard-list-columns": faTableColumns,
  "lab-dashboard-welcome": faSun,
  "lab-contact-details": faIdCard,
  "lab-contact-card": faIdCard,
  "lab-contact-notes": faComments,
  "lab-notes-activity": faComments,
  "lab-sidebar": faTableColumns,
  "lab-test-layout": faTableColumns,
  "lab-user-profile": faCircleUser,
  "lab-login-form": faLock,
  "lab-register-form": faUserShield,
  "lab-otp-form": faUserShield,
  "lab-passkey-login-form": faUserShield,
  "lab-social-auth-form": faUserShield,
  "lab-social-register-form": faUserShield,
  "404-page": faMagnifyingGlass,
  "403-page": faLock,
  "app-setup": faGears,
  carousel: faLayerGroup,
  "video-player": faVideo,
  "audio-player": faPlay,
  checkbox: faSquareCheck,
  "color-picker": faPalette,
  "command-palette": faTerminal,
  "context-menu": faMousePointer,
  "data-grid": faTableCells,
  "date-picker": faCalendar,
  "datetime-picker": faCalendarDays,
  dialog: faComments,
  drawer: faDoorOpen,
  "dropdown-menu": faCaretDown,
  "email-input": faEnvelope,
  "empty-state": faInbox,
  badge: faTags,
  avatar: faCircleUser,
  "avatar-group": faUsers,
  list: faList,
  "description-list": faClipboardList,
  divider: faMinus,
  "content-timeline": faTimeline,
  "tree-view": faSitemap,
  "masonry-grid": faGrip,
  "property-grid": faTableCells,
  stack: faGripLines,
  columns: faTableColumns,
  grid: faBorderAll,
  splitter: faGripLinesVertical,
  "resize-handle": faGripLinesVertical,
  "resizable-panel": faUpRightAndDownLeftFromCenter,
  "dock-layout": faTableColumns,
  "three-pane-layout": faTableColumns,
  "scroll-area": faMaximize,
  "custom-scrollbar": faBars,
  "aspect-ratio": faExpandAlt,
  container: faObjectGroup,
  spacer: faMinus,
  breadcrumb: faChevronRight,
  pagination: faPager,
  "page-header": faHeading,
  toolbar: faWrench,
  "application-header": faWindowMaximize,
  "application-footer": faWindowMaximize,
  "bottom-navigation": faMobileScreen,
  "navigation-rail": faBars,
  "split-button": faCaretDown,
  fab: faPlus,
  tile: faBorderAll,
  tiles: faGrip,
  "stat-tile": faChartColumn,
  "stat-tiles": faChartColumn,
  map: faGlobe,
  "property-inspector": faListCheck,
  "filter-builder": faFilter,
  "query-builder": faCodeBranch,
  "rule-builder": faGavel,
  "permissions-matrix": faUserShield,
  "dual-list-builder": faRightLeft,
  scheduler: faCalendarWeek,
  "kanban-board": faColumns,
  calendar: faCalendarDays,
  "resource-planner": faTimeline,
  "json-viewer": faCode,
  statistic: faChartColumn,
  icon: faIcons,
  "icon-badge": faBell,
  spinner: faSpinner,
  clock: faClock,
  portal: faDoorOpen,
  "portal-host": faObjectGroup,
  "visually-hidden": faEyeSlash,
  "focus-trap": faExpand,
  "keyboard-shortcut": faKeyboard,
  "hotkey-manager": faKeyboard,
  "copy-button": faCopy,
  clipboard: faClipboardList,
  "theme-provider": faMoon,
  "theme-switcher": faSun,
  "resize-observer": faExpand,
  "intersection-observer": faEye,
  "file-upload": faCloudArrowUp,
  "image-crop-upload": faCircleUser,
  "hidden-input": faEyeSlash,
  "image-gallery": faLayerGroup,
  "image-thumbnail": faClone,
  lightbox: faWindowMaximize,
  "mega-menu": faTableColumns,
  modal: faWindowMaximize,
  "model-gallery": faLayerGroup,
  "model-lightbox": faCube,
  "model-thumbnail": faClone,
  "model-viewer": faCube,
  "month-picker": faCalendarDays,
  "number-input": faHashtag,
  panel: faWindowRestore,
  section: faTableColumns,
  "password-input": faLock,
  popover: faMessage,
  "radio-group": faCircleDot,
  "chip-input": faTags,
  "choice-chips": faTags,
  "range-slider": faSliders,
  "reset-button": faRotateLeft,
  "search-input": faMagnifyingGlass,
  select: faCaretDown,
  "show-more": faEllipsis,
  sidebar: faBars,
  skeleton: faGripLines,
  "alert": faTriangleExclamation,
  "submit-button": faPaperPlane,
  switch: faToggleOn,
  table: faTable,
  tabs: faTableCells,
  "text-input": faFont,
  textarea: faAlignLeft,
  "note-composer": faNoteSticky,
  "rich-text-field": faPenToSquare,
  "filter-select": faFilter,
  "multi-select": faSquareCheck,
  "transfer-list": faRightLeft,
  "password-strength-field": faLock,
  "rating-input": faStar,
  "segmented-control": faGrip,
  "slider-range": faSliders,
  "phone-number-input": faPhone,
  "country-picker": faGlobe,
  "tree-select": faSitemap,
  cascader: faLayerGroup,
  "theme-toggle": faSun,
  "accent-color-picker": faPalette,
  "icon-picker": faIcons,
  "emoji-picker": faFaceSmile,
  "time-picker": faClock,
  toast: faBell,
  tooltip: faCircleInfo,
  "top-navigation": faSitemap,
  "url-input": faLink,
  "week-picker": faCalendarWeek,
  "bar-chart-vertical": faChartBar,
  "bar-chart-horizontal": faChartBar,
  "grouped-bar-chart": faChartBar,
  "stacked-bar-chart": faChartBar,
  "stacked-bar-chart-100": faChartBar,
  "line-chart": faChartLine,
  "multi-line-chart": faChartLine,
  "area-chart": faChartArea,
  "stacked-area-chart": faChartArea,
  "spline-chart": faChartLine,
  "pie-chart": faChartPie,
  "donut-chart": faChartPie,
  "scatter-plot": faChartLine,
  "bubble-chart": faCircleDot,
  "radar-chart": faChartPie,
  "polar-area-chart": faChartPie,
  "funnel-chart": faFilter,
  "pyramid-chart": faLayerGroup,
  "ohlc-chart": faChartColumn,
  "range-area-chart": faChartArea,
  "range-bar-chart": faChartBar,
  "error-bar-chart": faChartColumn,
  "parallel-coordinates": faChartLine,
  "contour-plot": faGrip,
  "surface-plot": faCube,
  "bullet-chart": faBullseye,
  "pareto-chart": faChartBar,
};

const categoryIcons: Record<ComponentCategory, IconDefinition> = {
  content: faLayerGroup,
  dashboard: faGrip,
  forms: faClipboardList,
  graphs: faChartLine,
  labs: faFlask,
  overlays: faClone,
  system: faGears,
};

const navigationGroupIcons: Record<string, IconDefinition> = {
  Application: faWindowMaximize,
  Accordion: faList,
  Data: faTable,
  Builders: faWrench,
  Planning: faCalendarDays,
  Layout: faTableColumns,
  "3D Assets": faCube,
  Images: faImage,
  Maps: faGlobe,
  Navigation: faSitemap,
  Tiles: faBorderAll,
  Utilities: faWrench,
  Dashboard: faGrip,
  Authentication: faUserShield,
  Forms: faClipboardList,
  "Bar Charts": faChartBar,
  "Line Charts": faChartLine,
  "Radial Charts": faChartPie,
  "Point Charts": faCircleDot,
  "Flow Charts": faFilter,
};

export function getOverviewIcon(): IconDefinition {
  return faGrip;
}

export function getNavigationGroupIcon(label: string): IconDefinition {
  return navigationGroupIcons[label] ?? faCube;
}

export function getComponentIcon(slug: ControlSlug): IconDefinition {
  return componentIcons[slug] ?? faCube;
}

export function getCategoryIcon(category: ComponentCategory): IconDefinition {
  return categoryIcons[category];
}
