import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAlignLeft,
  faBars,
  faBullseye,
  faChartColumn,
  faBell,
  faCalendar,
  faCalendarDays,
  faCalendarWeek,
  faCaretDown,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faCircleDot,
  faCircleInfo,
  faCircleUser,
  faClipboardList,
  faClone,
  faCloudArrowUp,
  faClock,
  faCode,
  faComments,
  faCopy,
  faCube,
  faDoorOpen,
  faEllipsis,
  faEnvelope,
  faExpand,
  faEye,
  faEyeSlash,
  faFilter,
  faFont,
  faGlobe,
  faGrip,
  faGripLines,
  faIcons,
  faHashtag,
  faImage,
  faInbox,
  faKeyboard,
  faLayerGroup,
  faLink,
  faList,
  faLock,
  faMagnifyingGlass,
  faMessage,
  faMinus,
  faMoon,
  faMousePointer,
  faObjectGroup,
  faPalette,
  faPaperPlane,
  faPenToSquare,
  faPhone,
  faRotateLeft,
  faRightLeft,
  faSitemap,
  faSliders,
  faSpinner,
  faSquare,
  faSquareCheck,
  faStar,
  faSun,
  faTable,
  faTableCells,
  faTableColumns,
  faTags,
  faTerminal,
  faTimeline,
  faToggleOn,
  faTriangleExclamation,
  faUsers,
  faWindowMaximize,
  faWindowRestore,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";
import type { ComponentCategory, ControlSlug } from "./types";

const componentIcons: Record<ControlSlug, IconDefinition> = {
  accordion: faList,
  "accordion-group": faLayerGroup,
  button: faSquare,
  card: faClone,
  "kpi-card": faChartColumn,
  "stat-card": faUsers,
  "gauge": faBullseye,
  carousel: faLayerGroup,
  checkbox: faSquareCheck,
  "color-picker": faPalette,
  "command-palette": faTerminal,
  "context-menu": faMousePointer,
  "data-grid": faTableCells,
  "date-picker": faCalendar,
  "datetime-picker": faCalendarDays,
  dialog: faComments,
  drawer: faDoorOpen,
  "dropdown-menu": faCaretDown,
  "email-input": faEnvelope,
  "empty-state": faInbox,
  badge: faTags,
  avatar: faCircleUser,
  "avatar-group": faUsers,
  list: faList,
  "description-list": faClipboardList,
  divider: faMinus,
  "content-timeline": faTimeline,
  "tree-view": faSitemap,
  "masonry-grid": faGrip,
  "property-grid": faTableCells,
  "json-viewer": faCode,
  statistic: faChartColumn,
  icon: faIcons,
  spinner: faSpinner,
  portal: faDoorOpen,
  "portal-host": faObjectGroup,
  "visually-hidden": faEyeSlash,
  "focus-trap": faExpand,
  "keyboard-shortcut": faKeyboard,
  "hotkey-manager": faKeyboard,
  "copy-button": faCopy,
  clipboard: faClipboardList,
  "theme-provider": faMoon,
  "theme-switcher": faSun,
  "resize-observer": faExpand,
  "intersection-observer": faEye,
  "file-upload": faCloudArrowUp,
  "hidden-input": faEyeSlash,
  "image-gallery": faLayerGroup,
  "image-thumbnail": faClone,
  lightbox: faWindowMaximize,
  "mega-menu": faTableColumns,
  modal: faWindowMaximize,
  "model-gallery": faLayerGroup,
  "model-lightbox": faCube,
  "model-thumbnail": faClone,
  "model-viewer": faCube,
  "month-picker": faCalendarDays,
  "number-input": faHashtag,
  panel: faWindowRestore,
  section: faTableColumns,
  "password-input": faLock,
  popover: faMessage,
  "radio-group": faCircleDot,
  "chip-input": faTags,
  "range-slider": faSliders,
  "reset-button": faRotateLeft,
  "search-input": faMagnifyingGlass,
  select: faCaretDown,
  "show-more": faEllipsis,
  sidebar: faBars,
  skeleton: faGripLines,
  "alert": faTriangleExclamation,
  "submit-button": faPaperPlane,
  switch: faToggleOn,
  table: faTable,
  tabs: faTableCells,
  "text-input": faFont,
  textarea: faAlignLeft,
  "rich-text-field": faPenToSquare,
  "filter-select": faFilter,
  "multi-select": faSquareCheck,
  "transfer-list": faRightLeft,
  "password-strength-field": faLock,
  "rating-input": faStar,
  "segmented-control": faGrip,
  "slider-range": faSliders,
  "phone-number-input": faPhone,
  "country-picker": faGlobe,
  "tree-select": faSitemap,
  cascader: faLayerGroup,
  "theme-toggle": faSun,
  "accent-color-picker": faPalette,
  "icon-picker": faIcons,
  "time-picker": faClock,
  toast: faBell,
  tooltip: faCircleInfo,
  "top-navigation": faSitemap,
  "url-input": faLink,
  "week-picker": faCalendarWeek,
  "bar-chart-vertical": faChartBar,
  "bar-chart-horizontal": faChartBar,
  "grouped-bar-chart": faChartBar,
  "stacked-bar-chart": faChartBar,
  "stacked-bar-chart-100": faChartBar,
  "line-chart": faChartLine,
  "multi-line-chart": faChartLine,
  "area-chart": faChartArea,
  "stacked-area-chart": faChartArea,
  "spline-chart": faChartLine,
  "pie-chart": faChartPie,
  "donut-chart": faChartPie,
  "scatter-plot": faChartLine,
  "bubble-chart": faCircleDot,
  "radar-chart": faChartPie,
  "polar-area-chart": faChartPie,
  "funnel-chart": faFilter,
  "pyramid-chart": faLayerGroup,
  "ohlc-chart": faChartColumn,
  "range-area-chart": faChartArea,
  "range-bar-chart": faChartBar,
  "error-bar-chart": faChartColumn,
  "parallel-coordinates": faChartLine,
  "contour-plot": faGrip,
  "surface-plot": faCube,
  "bullet-chart": faBullseye,
  "pareto-chart": faChartBar,
};

const categoryIcons: Record<ComponentCategory, IconDefinition> = {
  content: faLayerGroup,
  forms: faClipboardList,
  graphs: faChartLine,
  overlays: faClone,
};

const navigationGroupIcons: Record<string, IconDefinition> = {
  Accordion: faList,
  Data: faTable,
  "3D Assets": faCube,
  Images: faImage,
  Navigation: faSitemap,
  Utilities: faWrench,
  Dashboard: faGrip,
  "Bar Charts": faChartBar,
  "Line Charts": faChartLine,
  "Radial Charts": faChartPie,
  "Point Charts": faCircleDot,
  "Flow Charts": faFilter,
};

export function getOverviewIcon(): IconDefinition {
  return faGrip;
}

export function getNavigationGroupIcon(label: string): IconDefinition {
  return navigationGroupIcons[label] ?? faCube;
}

export function getComponentIcon(slug: ControlSlug): IconDefinition {
  return componentIcons[slug] ?? faCube;
}

export function getCategoryIcon(category: ComponentCategory): IconDefinition {
  return categoryIcons[category];
}
