import type { ControlSlug } from "./types";
import { getControl } from "./registry";

const componentDocumentation: Partial<Record<ControlSlug, string>> = {
  "bar-chart-vertical": "## Overview\n\nVertical bar chart powered by the shared `Chart` component.\n\n## When to use\n\n- Comparing one metric across compact categories.\n- Showing simple dashboard totals.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `variant` | `ChartVariant` | — | Selects the visual chart type. |\n| `data` | `ChartDatum[]` | demo data | Category data used by bars, radial, funnel, and point charts. |\n| `series` | `ChartSeries[]` | demo series | Multi-series data used by grouped, stacked, multi-line, and area charts. |\n| `palette` | `ChartPalette` | `\"opus\"` | Opus, cool, warm, or mono palette. |\n| `height` | `number` | `280` | Standard chart viewport height. |\n| `maximise` | `boolean` | `false` | Allows wide chart types such as bars, lines, areas, and point charts to fill available space. |\n| `showGrid` | `boolean` | `false` | Shows chart grid lines where relevant. |\n| `showLegend` | `boolean` | `true` | Shows series/category legend. |\n| `showValues` | `boolean` | `false` | Shows visible value labels where supported. |\n\n## Accessibility\n\n- Renders an SVG with `role=\"img\"` and an accessible label from the chart title.\n- Keep source data available in adjacent tables when exact values matter.",
  "accordion": "## Overview\n\nExpandable section.\n\n## When to use\n\n- FAQs and disclosure.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Trigger label. |\n| `children` | `ReactNode` | \u2014 | Panel. |\n\n## Accessibility\n\n- `aria-expanded` on trigger.\n\n## Related\n\n- [Accordion group](/documentation/components/accordion-group)",
  "accordion-group": "## Overview\n\nCoordinated accordion items.\n\n## When to use\n\n- FAQ groups.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `type` | `AccordionGroupType` | \u2014 | Single or multiple open. |\n| `children` | `Accordion[]` | \u2014 | Items. |\n\n## Accessibility\n\n- Group has `role=\"group\"`.",
  "button": "## Overview\n\nStandalone action button with multiple visual variants.\n\n## When to use\n\n- Primary actions on forms and dialogs.\n- Secondary or destructive actions when paired with a primary button.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `children` | `ReactNode` | \u2014 | Button label or content. |\n| `variant` | `ButtonVariant` | `\"primary\"` | Visual style: primary, secondary, success, danger, warning, info, light, dark, link. |\n| `disabled` | `boolean` | `false` | Disables interaction. |\n| `type` | `\"button\" \\| \"submit\" \\| \"reset\"` | `\"button\"` | Native button type. |\n\n## Accessibility\n\n- Use descriptive button text or `aria-label` when the label is icon-only.",
  "card": "## Overview\n\nCompact content surface.\n\n## When to use\n\n- Dashboard tiles and previews.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Heading. |\n| `children` | `ReactNode` | \u2014 | Body. |\n\n## Accessibility\n\n- Semantic `article` with `h3`.",
  "stat-card": "## Overview\n\nCompact KPI tile for dashboard summaries.\n\n## When to use\n\n- Headline metrics such as customers, orders, revenue, or active users.\n- Pair multiple stat cards in a grid for at-a-glance dashboards.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `label` | `string` | \u2014 | Metric name. |\n| `value` | `string` | \u2014 | Primary metric value. |\n| `change` | `string` | \u2014 | Optional delta label such as `11.01%`. |\n| `trend` | `\"up\" \\| \"down\"` | \u2014 | Trend direction for the delta badge. |\n| `icon` | `ReactNode` | \u2014 | Optional leading icon. |\n| `density` | `SurfaceDensity` | `\"comfortable\"` | Spacing scale. |\n\n## Accessibility\n\n- Semantic `article` with readable label and value text.",
  "gauge": "## Overview\n\nDashboard progress gauge with half and full variants, optional summary, and footer metrics.\n\n## When to use\n\n- Goal or quota tracking on dashboards.\n- Executive summary cards with one primary progress value.\n- Compact KPI cards where the circular stat is the primary visual.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Widget heading. |\n| `subtitle` | `string` | \u2014 | Supporting description under the title. |\n| `value` | `number` | \u2014 | Progress percentage from 0\u2013100. |\n| `trackColor` | `string` | theme border | Gauge track stroke colour. |\n| `valueColor` | `string` | Opus accent | Gauge data range stroke colour. |\n| `variant` | `\"half\" \\| \"full\"` | `\"half\"` | Half arc or full circular gauge. |\n| `change` | `string` | \u2014 | Optional delta badge such as `+10%`. |\n| `changeTrend` | `\"up\" \\| \"down\"` | `\"up\"` | Delta badge direction. |\n| `summary` | `string` | \u2014 | Supporting copy below the gauge. |\n| `footer` | `{ color?, label, value, trend? }[]` | \u2014 | Optional footer metrics. Each item can define its own accent line colour. |\n| `density` | `SurfaceDensity` | `\"comfortable\"` | Spacing scale. |",
  "carousel": "## Overview\n\nImage carousel with nav and pips.\n\n## When to use\n\n- Hero rotators and galleries.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `images` | `GalleryImage[]` | \u2014 | Slides. |\n| `loop` | `boolean` | \u2014 | Wrap slides. |\n\n## Accessibility\n\n- Keyboard arrows; live region for slide.\n\n## Related\n\n- [Lightbox](/documentation/components/lightbox)",
  "checkbox": "## Overview\n\nBoolean checkbox with round or square shape variants.\n\n## When to use\n\n- Single on/off preferences.\n- Options that do not require a radio group.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `checked` | `boolean` | \u2014 | Controlled checked state. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `shape` | `\"round\" \\| \"square\"` | `\"square\"` | Checkbox shape. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- Uses native checkbox with visible label.",
  "color-picker": "## Overview\n\nColour input with swatch and hex display.\n\n## When to use\n\n- Theme or branding pickers.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Hex colour. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- `aria-valuetext` announces hex value.",
  "command-palette": "## Overview\n\nSearchable command launcher.\n\n## When to use\n\n- Global shortcuts and actions.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `open` | `boolean` | \u2014 | Visible. |\n| `items` | `CommandPaletteItem[]` | \u2014 | Commands. |\n| `onClose` | `() => void` | \u2014 | Close handler. |\n\n## Accessibility\n\n- Combobox search with focus trap.",
  "context-menu": "## Overview\n\nRight-click pointer menu.\n\n## When to use\n\n- Contextual row/card actions.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `items` | `DropdownMenuItemData[]` | \u2014 | Items. |\n| `label` | `string` | \u2014 | Target label. |\n\n## Accessibility\n\n- Requires `ContextMenuProvider`. Shift+F10 opens menu.\n\n## Related\n\n- [Dropdown menu](/documentation/components/dropdown-menu)",
  "data-grid": "## Overview\n\nScrollable grid with sort and filter.\n\n## When to use\n\n- Large datasets.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `columns` | `DataGridColumn[]` | \u2014 | Columns. |\n| `rows` | `DataGridRow[]` | \u2014 | Rows. |\n| `sortable` | `boolean` | \u2014 | Sorting. |\n| `filterable` | `boolean` | \u2014 | Filtering. |\n\n## Accessibility\n\n- `aria-sort` on sortable headers.",
  "date-picker": "## Overview\n\nNative date input (`type=\"date\"`).\n\n## When to use\n\n- Date selection with browser-native picker.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Input value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "datetime-picker": "## Overview\n\nNative date and time input (`type=\"datetime-local\"`).\n\n## When to use\n\n- Date and time selection with browser-native picker.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Input value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "dialog": "## Overview\n\nConfirmation dialog with preset action sets.\n\n## When to use\n\n- Confirmations and destructive gates.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `open` | `boolean` | \u2014 | Visible. |\n| `title` | `string` | \u2014 | Heading. |\n| `description` | `string` | \u2014 | Message. |\n| `actionSet` | `DialogActionSet` | \u2014 | Buttons preset. |\n| `onClose` | `() => void` | \u2014 | Close handler. |\n\n## Accessibility\n\n- Focus trap, dialog role, scroll lock.",
  "drawer": "## Overview\n\nEdge-attached overlay panel.\n\n## When to use\n\n- Filters, inspectors, nav.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `open` | `boolean` | \u2014 | Visible. |\n| `title` | `string` | \u2014 | Heading. |\n| `side` | `DrawerSide` | `\"right\"` | Edge. |\n| `onClose` | `() => void` | \u2014 | Close handler. |\n\n## Accessibility\n\n- Focus trap and restore on close.",
  "dropdown-menu": "## Overview\n\nAnchored action menu.\n\n## When to use\n\n- Toolbar and nav menus.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `items` | `DropdownMenuItemData[]` | \u2014 | Menu items. |\n| `label` | `string` | \u2014 | Trigger label. |\n| `placement` | `DropdownMenuPlacement` | \u2014 | Position. |\n\n## Accessibility\n\n- Arrow keys, Home, End, Escape.",
  "email-input": "## Overview\n\nEmail variant of TextField.\n\n## When to use\n\n- Collecting email values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"email\"` | `\"email\"` | Fixed input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "empty-state": "## Overview\n\nEmpty list placeholder.\n\n## When to use\n\n- Zero results and onboarding.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Heading. |\n| `description` | `string` | \u2014 | Guidance. |\n\n## Accessibility\n\n- Labelled `section`.",
  "file-upload": "## Overview\n\nFile picker with styled drop zone.\n\n## When to use\n\n- Document and image uploads.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `onChange` | `(event) => void` | \u2014 | Selection handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "hidden-input": "## Overview\n\nHidden form field.\n\n## When to use\n\n- Tokens and non-editable ids.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `name` | `string` | \u2014 | Field name. |\n| `value` | `string` | \u2014 | Submitted value. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- Not exposed to assistive tech.",
  "image-gallery": "## Overview\n\nGrid of lightbox thumbnails.\n\n## When to use\n\n- Photo grids.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `images` | `GalleryImage[]` | \u2014 | Items. |\n| `columns` | `2 \\| 3 \\| 4` | \u2014 | Grid columns. |\n\n## Accessibility\n\n- `aria-label` on gallery container.",
  "image-thumbnail": "## Overview\n\nThumbnail with optional lightbox.\n\n## When to use\n\n- Single image previews.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `image` | `GalleryImage` | \u2014 | Image. |\n| `size` | `ImageThumbnailSize` | \u2014 | Scale. |",
  "lightbox": "## Overview\n\nFull-screen image viewer.\n\n## When to use\n\n- Enlarge thumbnails.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `image` | `GalleryImage` | \u2014 | Image. |\n| `trigger` | `ReactNode` | \u2014 | Optional trigger. |\n\n## Accessibility\n\n- Focus trap; Escape dismisses.",
  "mega-menu": "## Overview\n\nLarge grouped navigation panel with optional featured callout.\n\n## When to use\n\n- Product navigation with grouped destinations.\n- Documentation hubs with a promotional sidebar.\n- Standalone menu surfaces outside a full app menu bar.\n\n## Data\n\nPass a `menus` array. Each entry defines one top-level trigger and its panel content:\n\n- `id` and `label` identify the menu trigger.\n- `sections` defines the column count; each section is one column with a title and `items` rows.\n- `featured` is an optional promotional sidebar with `eyebrow`, `title`, `description`, and `actionLabel`.\n\nUse `staticPanel` to render a single menu panel inline without a trigger (for docs and previews).\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `menus` | `MegaMenuConfig[]` | \u2014 | Primary data source; pass one item for a single menu. |\n| `sections` | `MegaMenuSection[]` | \u2014 | Legacy fallback when `menus` is omitted. |\n| `featured` | `MegaMenuFeatured` | \u2014 | Legacy fallback featured panel for a single menu. |\n| `density` | `SurfaceDensity` | `\"comfortable\"` | Spacing scale. |\n| `staticPanel` | `boolean` | `false` | Render the panel inline without a trigger button. |\n| `open` | `boolean` | \u2014 | Controlled open state for standalone dropdown usage. |\n\n## Accessibility\n\n- Menu trigger exposes `aria-haspopup`, `aria-expanded`, and `aria-controls` when not using `staticPanel`.\n- Escape and outside-click dismissal are configurable.\n\n## Related\n\n- [Top navigation](/documentation/components/top-navigation)",
  "model-gallery": "## Overview\n\nGrid of 3D asset thumbnails.\n\n## When to use\n\n- Browsing game props, enemies, and environment assets.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `assets` | `ModelAsset[]` | \u2014 | Model items. |\n| `columns` | `2 \\| 3 \\| 4` | `4` | Grid columns. |\n| `thumbnailSize` | `ModelThumbnailSize` | `\"small\"` | Preview scale. |\n\n## Accessibility\n\n- Each thumbnail opens a labelled dialog for the selected model.",
  "model-lightbox": "## Overview\n\nFull-screen 3D model viewer.\n\n## When to use\n\n- Inspecting a single GLB model from a thumbnail or action button.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `asset` | `ModelAsset` | \u2014 | Model metadata and source. |\n| `trigger` | `ReactNode` | \u2014 | Optional trigger content. |\n| `dismissOnBackdrop` | `boolean` | `true` | Close when clicking the backdrop. |\n\n## Accessibility\n\n- Uses a dialog role, focus restore, and optional Escape dismiss.",
  "model-thumbnail": "## Overview\n\nCompact 3D asset preview.\n\n## When to use\n\n- Single asset cards and gallery items.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `asset` | `ModelAsset` | \u2014 | Model metadata and source. |\n| `size` | `ModelThumbnailSize` | `\"medium\"` | Preview scale. |\n| `openInLightbox` | `boolean` | `true` | Opens full model preview on click. |",
  "model-viewer": "## Overview\n\nInteractive 3D model preview.\n\n## When to use\n\n- Showing GLB assets inline with orbit controls and automatic rotation.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `asset` | `ModelAsset` | \u2014 | Model metadata and source. |\n| `autoRotate` | `boolean` | `true` | Rotate the asset automatically. |\n| `cameraControls` | `boolean` | `true` | Allow pointer orbit and zoom. |\n\n## Accessibility\n\n- Uses `alt` metadata for the model-viewer element and visible captions.",
  "modal": "## Overview\n\nCentred overlay for longer content.\n\n## When to use\n\n- Forms and multi-step flows.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `open` | `boolean` | \u2014 | Visible. |\n| `title` | `string` | \u2014 | Heading. |\n| `size` | `ModalSize` | `\"medium\"` | Width. |\n| `onClose` | `() => void` | \u2014 | Close handler. |\n\n## Accessibility\n\n- Focus trap; Tab cycles within modal.",
  "month-picker": "## Overview\n\nNative month input (`type=\"month\"`).\n\n## When to use\n\n- Month selection with browser-native picker.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Input value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "number-input": "## Overview\n\nNumber field with stepper buttons.\n\n## When to use\n\n- Quantities and bounded numbers.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `number` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `min` | `number` | \u2014 | Minimum. |\n| `max` | `number` | \u2014 | Maximum. |\n| `step` | `number` | `1` | Step size. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- Steppers disable at min/max.",
  "panel": "## Overview\n\nStructured page section.\n\n## When to use\n\n- Settings groups and docs sections.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Heading. |\n| `description` | `string` | \u2014 | Subtitle. |\n| `children` | `ReactNode` | \u2014 | Body. |\n\n## Accessibility\n\n- Semantic `section` with header/footer.",
  "section": "## Overview\n\nResponsive page layout primitive with rows and columns.\n\n## When to use\n\n- Page-level layouts that stack on mobile and expand on tablet/desktop.\n- Sidebar plus multi-column main areas.\n- Equal-width columns that stay on one row and fill the available width.\n\n## Mental model\n\n- `Section` \u2014 vertical stack of rows with optional title.\n- `Section.Row` \u2014 one responsive band configured with `sidebar` and `columns`.\n- `Section.Column` \u2014 optional slot for custom span or width.\n\n## Configuration\n\n| Setting | Values | Description |\n| --- | --- | --- |\n| `sidebar` | `none`, `left`, `right` | Optional sidebar track beside the main area. |\n| `columns` | `1`\u2013`5` | Number of equal content columns in the main area. |\n| `stackBelow` | `mobile`, `tablet`, `never` | When layouts collapse to one column. |\n| `sidebarRatio` | `1:2`, `1:3`, `2:3` | Sidebar width vs main area when a sidebar is active. |\n\nWhen `sidebar` is set with `columns` greater than 1, the main area uses a nested `Section.Row` for the content columns.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `title` | `string` | \u2014 | Section heading. |\n| `description` | `string` | \u2014 | Section subtitle. |\n| `gap` | `\"sm\" \\| \"md\" \\| \"lg\"` | `\"md\"` | Vertical gap between rows. |\n| `sidebar` | `\"none\" \\| \"left\" \\| \"right\"` | `\"none\"` | Sidebar placement on `Section.Row`. |\n| `columns` | `1`\u2013`5` | `1` | Equal content columns. |\n| `stackBelow` | `\"mobile\" \\| \"tablet\" \\| \"never\"` | `\"mobile\"` | Collapse breakpoint. |\n| `template` | `Partial<Record<breakpoint, string>>` | \u2014 | Custom CSS grid templates per breakpoint. |\n\n## Accessibility\n\n- Semantic `section` with optional `h2` heading.\n\n## Related\n\n- [Panel](/documentation/components/panel)\n- [Card](/documentation/components/card)",
  "password-input": "## Overview\n\nPassword variant of TextField.\n\n## When to use\n\n- Collecting password values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"password\"` | `\"password\"` | Fixed input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "popover": "## Overview\n\nAnchored floating panel.\n\n## When to use\n\n- Inline help and compact forms.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `trigger` | `ReactNode` | \u2014 | Trigger. |\n| `title` | `string` | \u2014 | Optional title. |\n| `placement` | `PopoverPlacement` | `\"bottom\"` | Side. |\n\n## Accessibility\n\n- `aria-expanded` on trigger.",
  "radio-group": "## Overview\n\nGrouped radio options with shared selection state.\n\n## When to use\n\n- Mutually exclusive choices.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Selected value. |\n| `onChange` | `(value: string) => void` | \u2014 | Selection handler. |\n| `options` | `ChoiceOption[]` | \u2014 | Radio options. |\n| `shape` | `\"round\" \\| \"square\"` | `\"round\"` | Indicator shape. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "chip-input": "## Overview\n\nTokenised text input that converts typed values into removable chips. Also known as tag input, token input, or pills input.\n\n## When to use\n\n- Email recipients, user permissions, and keyword fields.\n- Labels, categories, and skills where values should stay visible.\n- Any repeated free-text values that benefit from compact pill display.\n\n## Presets\n\nBuild specialised flows on the same component:\n\n- **Chip input** — generic multi-value entry.\n- **Tag input** — labels and keywords.\n- **Token input** — recipients, users, and permissions.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string[]` | \u2014 | Current chips. |\n| `onChange` | `(value: string[]) => void` | \u2014 | Chip list handler. |\n| `placeholder` | `string` | \u2014 | Shown when empty. |\n| `variant` | `\"filled\" \\| \"outlined\" \\| \"soft\" \\| \"glass\" \\| \"gradient\"` | `\"soft\"` | Chip visual style. |\n| `readOnly` | `boolean` | `false` | Show chips without editing. |\n| `disabled` | `boolean` | `false` | Disables interaction. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Interaction\n\n- Press **Enter**, **Comma**, or **Tab** to commit the current text as a chip.\n- Press **Backspace** on an empty input to remove the last chip.\n- Click **\u00d7** on a chip to remove it.\n\n## Chip variants\n\n| Variant | Description |\n| --- | --- |\n| Filled | Solid chip background. |\n| Outlined | Border-only chips. |\n| Soft | Accent-tinted fill. |\n| Glass | Frosted translucent chips. |\n| Gradient | Purple/blue Opus gradient border. |\n\n## States\n\nDefault, hover, focus, disabled, error, and read-only are supported on the field and chips.\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Chips expose remove buttons with descriptive `aria-label` values.\n\n## Related\n\n- [Text input](/documentation/components/text-input)\n- [Select](/documentation/components/select)",
  "range-slider": "## Overview\n\nRange slider with value display.\n\n## When to use\n\n- Volume, opacity, approximate values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `number` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `min` | `number` | \u2014 | Min. |\n| `max` | `number` | \u2014 | Max. |\n| `step` | `number` | `1` | Step. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "reset-button": "## Overview\n\nForm reset button using `Button` with `type=\"reset\"`.\n\n## When to use\n\n- Forms where users should restore default field values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `children` | `ReactNode` | \u2014 | Button label or content. |\n| `variant` | `ButtonVariant` | `\"primary\"` | Visual style: primary, secondary, success, danger, warning, info, light, dark, link. |\n| `disabled` | `boolean` | `false` | Disables interaction. |\n| `type` | `\"button\" \\| \"submit\" \\| \"reset\"` | `\"button\"` | Native button type. |",
  "search-input": "## Overview\n\nSearch variant of TextField.\n\n## When to use\n\n- Collecting search values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"search\"` | `\"search\"` | Fixed input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "select": "## Overview\n\nDropdown select.\n\n## When to use\n\n- Choosing from predefined options.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Selected value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `options` | `string[]` | \u2014 | Options list. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "show-more": "## Overview\n\nClamp long text with toggle.\n\n## When to use\n\n- Truncated descriptions.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `children` | `ReactNode` | \u2014 | Content. |\n| `maxLines` | `number` | `3` | Clamp lines. |\n\n## Accessibility\n\n- Toggle has `aria-expanded`.",
  "sidebar": "## Overview\n\nNavigation rail and layout shell.\n\n## When to use\n\n- App and docs shells.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `side` | `SidebarSide` | `\"left\"` | Position. |\n| `collapsed` | `boolean` | \u2014 | Icon-only mode. |\n\n## Accessibility\n\n- Header is `h2`; groups labelled when collapsed.",
  "skeleton": "## Overview\n\nLoading placeholder.\n\n## When to use\n\n- Async content loading.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `variant` | `SkeletonVariant` | `\"text\"` | Shape. |\n| `lines` | `number` | `3` | Line count. |\n\n## Accessibility\n\n- `aria-busy=\"true\"` on container.",
  "alert": "## Overview\n\nDismissible inline banner.\n\n## When to use\n\n- Form errors and success.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `status` | `AlertStatus` | `\"error\"` | Tone. |\n| `title` | `string` | \u2014 | Heading. |\n| `description` | `string` | \u2014 | Detail. |\n\n## Accessibility\n\n- `role=\"alert\"` or `role=\"status\"`.",
  "submit-button": "## Overview\n\nForm submission button using `Button` with `type=\"submit\"`.\n\n## When to use\n\n- End of forms to commit user input.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `children` | `ReactNode` | \u2014 | Button label or content. |\n| `variant` | `ButtonVariant` | `\"primary\"` | Visual style: primary, secondary, success, danger, warning, info, light, dark, link. |\n| `disabled` | `boolean` | `false` | Disables interaction. |\n| `type` | `\"button\" \\| \"submit\" \\| \"reset\"` | `\"button\"` | Native button type. |",
  "switch": "## Overview\n\nToggle switch for on/off settings.\n\n## When to use\n\n- Settings that take effect immediately.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `checked` | `boolean` | \u2014 | Controlled on state. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- Switch uses switch semantics with associated label.",
  "table": "## Overview\n\nResponsive data table.\n\n## When to use\n\n- Read-only tabular data.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `columns` | `TableColumn[]` | \u2014 | Columns. |\n| `rows` | `TableRow[]` | \u2014 | Rows. |\n| `emptyMessage` | `string` | \u2014 | Empty copy. |\n\n## Accessibility\n\n- Empty cell uses `role=\"status\"`.",
  "tabs": "## Overview\n\nTabbed content navigation.\n\n## When to use\n\n- Related views without routing.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `items` | `TabItem[]` | \u2014 | Tabs. |\n| `value` | `string` | \u2014 | Active tab. |\n\n## Accessibility\n\n- Arrow keys move tab focus.",
  "telephone-input": "## Overview\n\nTelephone variant of TextField.\n\n## When to use\n\n- Collecting telephone values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"tel\"` | `\"tel\"` | Fixed input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "text-input": "## Overview\n\nSingle-line text input.\n\n## When to use\n\n- Names, titles, short text.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"text\"` | `\"text\"` | Input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "textarea": "## Overview\n\nMulti-line text with optional character limit.\n\n## When to use\n\n- Descriptions and comments.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `maxChars` | `number` | \u2014 | Max length. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- Character count in `aria-describedby` when limited.",
  "theme-toggle": "## Overview\n\nLight/dark theme switch.\n\n## When to use\n\n- App theme preference.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `\"light\" \\| \"dark\"` | \u2014 | Theme. |\n| `onChange` | `(theme) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.\n- `aria-pressed` on theme buttons.",
  "accent-color-picker": "## Overview\n\nPreset accent colour swatches for branding.\n\n## When to use\n\n- Let users pick an app accent colour from a curated palette.\n- Pair with `createAccentStyle()` to apply CSS custom properties.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Selected hex colour. |\n| `onChange` | `(value) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"flagged\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label wiring.\n- Swatches use `role=\"radiogroup\"` with `aria-checked` on each option.\n\n## Related\n\n- [Theme toggle](/documentation/components/theme-toggle)\n- [Colour picker](/documentation/components/color-picker)",
  "icon-picker": "## Overview\n\nSearchable Font Awesome icon picker with frosted icon badges.\n\n## When to use\n\n- Let users choose an icon from the solid Font Awesome set.\n- Pair with dashboard cards, metric tiles, and other icon slots.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Selected Font Awesome `iconName` such as `chart-column`. |\n| `onChange` | `(value) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `searchPlaceholder` | `string` | `\"Search icons\"` | Placeholder for the filter field. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label wiring.\n- Trigger exposes `aria-expanded` and listbox options use `aria-selected`.\n\n## Related\n\n- [Stat card](/documentation/components/stat-card)\n- [Metric tile](/documentation/components/metric-tile)",
  "time-picker": "## Overview\n\nNative time input (`type=\"time\"`).\n\n## When to use\n\n- Time selection with browser-native picker.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Input value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "toast": "## Overview\n\nFloating notification via ToastProvider.\n\n## When to use\n\n- Transient action feedback.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `status` | `AlertStatus` | \u2014 | Tone. |\n| `title` | `string` | \u2014 | Message. |\n\n## Accessibility\n\n- Use with `ToastProvider` and `useToast()`.\n\n## Related\n\n- [Alert](/documentation/components/alert)",
  "tooltip": "## Overview\n\nHelp icon with popup on hover, focus, or click.\n\n## When to use\n\n- Supplementary help beside labels.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `content` | `string` | \u2014 | Tooltip text. |\n| `label` | `string` | `\"More information\"` | Trigger label. |\n\n## Accessibility\n\n- `role=\"tooltip\"` and `aria-describedby` on trigger.",
  "top-navigation": "## Overview\n\nUnified app-style top navigation with normal dropdowns and a single MegaMenu item.\n\n## When to use\n\n- Desktop app chrome with top-level items such as App, File, Edit, View, Window, and Help.\n- Navigation where one top item needs a rich mega panel while the rest stay compact.\n\n## Data\n\nPass a single `menus` array to define the full bar in order. Each entry is one top-level label (`App`, `File`, `Edit`, …):\n\n| Field | Dropdown (`type: \"dropdown\"`) | Mega panel (`type: \"mega\"`) |\n| --- | --- | --- |\n| `id` | Menu id for `activeMenu` | Menu id for `activeMenu` |\n| `label` | Bar trigger text | Bar trigger text |\n| `items` | Flat dropdown rows | \u2014 |\n| `sections` | \u2014 | Grouped mega menu columns |\n| `featured` | \u2014 | Optional promotional sidebar |\n\n```tsx\nconst menus = [\n  { type: \"dropdown\", id: \"app\", label: \"App\", items: [...] },\n  { type: \"mega\", id: \"edit\", label: \"Edit\", sections: [...], featured: {...} },\n];\n\n<TopNavigation menus={menus} />\n```\n\nUse `activeMenu` + `onActiveMenuChange` for controlled open state.\n\nHandle link clicks with `onSelect` on `TopNavigation` for one shared handler, or `onSelect` on individual dropdown `items` / mega menu rows for per-link callbacks.\n\n```tsx\nconst handleSelect = (menuId, item) => setLastAction(`${menuId}: ${item.label}`);\n\n<TopNavigation menus={menus} onSelect={handleSelect} />\n```\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `menus` | `TopNavigationBarMenu[]` | default bar | Defines the full top navigation in order. |\n| `activeMenu` | `string \\| null` | `null` | Controlled active top menu id. |\n| `density` | `SurfaceDensity` | `\"comfortable\"` | Spacing scale. |\n| `showShortcuts` | `boolean` | `true` | Show keyboard shortcuts on dropdown items. |\n| `closeOnOutside` | `boolean` | `true` | Close menus on outside click. |\n| `closeOnEscape` | `boolean` | `true` | Close menus on Escape. |\n| `closeOnSelect` | `boolean` | `true` | Close menus after a link is selected. |\n| `onActiveMenuChange` | `(menuId) => void` | \u2014 | Called when the open menu changes. |\n| `onSelect` | `(menuId, item) => void` | \u2014 | Called when a dropdown or mega menu link is selected. |\n| `children` | `ReactNode` | \u2014 | Optional custom bar composition instead of `menus`. |\n\n## Accessibility\n\n- The bar uses a labelled `nav` landmark.\n- Dropdown and mega menu triggers expose expanded state and keyboard dismissal.\n\n## Related\n\n- [Mega menu](/documentation/components/mega-menu)\n- [Dropdown menu](/documentation/components/dropdown-menu)",
  "url-input": "## Overview\n\nURL variant of TextField.\n\n## When to use\n\n- Collecting url values.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `placeholder` | `string` | \u2014 | Placeholder. |\n| `type` | `\"url\"` | `\"url\"` | Fixed input type. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
  "week-picker": "## Overview\n\nNative week input (`type=\"week\"`).\n\n## When to use\n\n- Week selection with browser-native picker.\n\n## Props\n\n| Prop | Type | Default | Description |\n| --- | --- | --- | --- |\n| `value` | `string` | \u2014 | Input value. |\n| `onChange` | `(event) => void` | \u2014 | Change handler. |\n| `mode` | `\"stacked\" \\| \"flagged\"` | `\"stacked\"` | Layout mode for label and control. |\n| `labelPosition` | `\"left\" \\| \"right\"` | `\"left\"` | Label placement in flagged mode. |\n| `error` | `string` | \u2014 | Validation message; sets `aria-invalid` when present. |\n| `help` | `string` | \u2014 | Supplementary help text linked via `aria-describedby`. |\n| `required` | `boolean` | `false` | Marks the field as required for assistive tech. |\n\n## Accessibility\n\n- Wrapped in `FieldShell` for label, help, error, and required wiring.\n- Labels associate with controls via `htmlFor` / `id`.",
};

export function getComponentDocumentationMarkdown(slug: ControlSlug): string | null {
  const markdown = componentDocumentation[slug];
  if (markdown) {
    return markdown;
  }

  const control = getControl(slug);
  if (!control) {
    return null;
  }

  if (control.category === "graphs") {
    return [
      "## Overview",
      "",
      `${control.title} is rendered with the shared \`Chart\` component.`,
      "",
      "## When to use",
      "",
      control.description,
      "",
      "## Props",
      "",
      "| Prop | Type | Default | Description |",
      "| --- | --- | --- | --- |",
      "| `variant` | `ChartVariant` | — | Selects the visual chart type. |",
      "| `data` | `ChartDatum[]` | demo data | Category data used by bars, radial, funnel, and point charts. |",
      "| `series` | `ChartSeries[]` | demo series | Multi-series data used by grouped, stacked, multi-line, and area charts. |",
      "| `palette` | `ChartPalette` | `\"opus\"` | Opus, cool, warm, or mono palette. |",
      "| `height` | `number` | `280` | Chart viewport height in pixels. |",
      "| `maximise` | `boolean` | `false` | Allows wide chart types such as bars, lines, areas, and point charts to fill available space. |",
      "| `showAxis` | `boolean` | `false` | Shows data-driven X and Y axes on cartesian charts. |",
      "| `xAxisLabel` | `string` | — | Optional X axis title. |",
      "| `yAxisLabel` | `string` | — | Optional Y axis title. |",
      "| `highlightLabel` | `string` | — | Optional highlighted category for vertical bar charts. |",
      "| `showGrid` | `boolean` | `false` | Shows chart grid lines where relevant. |",
      "| `showLegend` | `boolean` | `true` | Shows series/category legend. |",
      "| `showValues` | `boolean` | `false` | Shows visible value labels where supported. |",
      "",
      "## Accessibility",
      "",
      "- Renders an SVG with `role=\"img\"` and an accessible label from the chart title.",
      "- Keep source data available in adjacent tables when exact numeric values matter.",
    ].join("\n");
  }

  return [
    "## Overview",
    "",
    control.description,
    "",
    "## Import",
    "",
    "```tsx",
    `import { ${control.componentName} } from "opus-react";`,
    "```",
  ].join("\n");
}
