import type { ControlSettingsBySlug, ControlSlug } from "./types";
import { chartDefaults } from "./chartDefaults";
import {
  defaultUserProfileMenuItemsJson,
  defaultUserProfilePhotoSrc,
  defaultUserProfilePhotoUploadMenuItemId,
} from "./userProfileDemoData";

const now = new Date();

function pad(value: number) {
  return String(value).padStart(2, "0");
}

function toDateValue(date: Date) {
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function toTimeValue(date: Date) {
  return `${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function toDateTimeValue(date: Date) {
  return `${toDateValue(date)}T${toTimeValue(date)}`;
}

function toMonthValue(date: Date) {
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}`;
}

function toWeekValue(date: Date) {
  const target = new Date(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()),
  );
  const dayNumber = target.getUTCDay() || 7;
  target.setUTCDate(target.getUTCDate() + 4 - dayNumber);
  const yearStart = new Date(Date.UTC(target.getUTCFullYear(), 0, 1));
  const week = Math.ceil(
    ((target.getTime() - yearStart.getTime()) / 86400000 + 1) / 7,
  );
  return `${target.getUTCFullYear()}-W${pad(week)}`;
}

const currentDateValue = toDateValue(now);
const currentTimeValue = toTimeValue(now);
const currentDateTimeValue = toDateTimeValue(now);
const currentMonthValue = toMonthValue(now);
const currentWeekValue = toWeekValue(now);

const baseFieldDefaults = {
  mode: "stacked" as const,
  labelPosition: "left" as const,
  errorEnabled: false,
  error: "This field is required",
  helpEnabled: false,
  help: "Optional help text for this field",
  required: false,
  size: "md" as const,
};

export const defaultSettings: ControlSettingsBySlug = {
  button: {
    variant: "primary",
    label: "Button",
    disabled: false,
    size: "md",
  },
  "submit-button": {
    variant: "primary",
    label: "Submit",
    disabled: false,
    size: "md",
  },
  "reset-button": {
    variant: "secondary",
    label: "Reset",
    disabled: false,
    size: "md",
  },
  checkbox: {
    ...baseFieldDefaults,
    label: "I agree to the Terms & Conditions",
    mode: "flagged",
    checked: false,
    shape: "square",
    size: "md",
  },
  switch: {
    ...baseFieldDefaults,
    label: "Enable notifications",
    mode: "flagged",
    checked: true,
  },
  "radio-group": {
    ...baseFieldDefaults,
    label: "Account type",
    value: "personal",
    shape: "round",
    size: "md",
    error: "Please select an account type",
    optionErrorsEnabled: false,
    optionError: "This option needs review",
  },
  "chip-input": {
    ...baseFieldDefaults,
    label: "Tags",
    value: ["Design", "React", "UI"],
    placeholder: "Add a tag…",
    placeholderEnabled: true,
    variant: "soft",
    preset: "tag-input",
    disabled: false,
    readOnly: false,
  },
  "choice-chips": {
    ...baseFieldDefaults,
    label: "Interests",
    value: ["design", "frontend"],
    options:
      "Design:design, Frontend:frontend, Research:research, Strategy:strategy",
    selectionMode: "multiple",
    variant: "soft",
    disabled: false,
    error: "Please select at least one interest",
  },
  "color-picker": {
    ...baseFieldDefaults,
    label: "Choose a colour",
    value: "#6D2BD9",
  },
  "date-picker": {
    ...baseFieldDefaults,
    label: "Date of birth",
    value: currentDateValue,
  },
  "time-picker": {
    ...baseFieldDefaults,
    label: "Start time",
    value: currentTimeValue,
  },
  "datetime-picker": {
    ...baseFieldDefaults,
    label: "Appointment",
    value: currentDateTimeValue,
  },
  "month-picker": {
    ...baseFieldDefaults,
    label: "Billing month",
    value: currentMonthValue,
  },
  "week-picker": {
    ...baseFieldDefaults,
    label: "Planning week",
    value: currentWeekValue,
  },
  "email-input": {
    ...baseFieldDefaults,
    label: "Email address",
    value: "jane.cooper@example.com",
  },
  "url-input": {
    ...baseFieldDefaults,
    label: "Website",
    value: "https://example.com",
  },
  "search-input": {
    ...baseFieldDefaults,
    label: "Search",
    value: "",
    placeholder: "Search contacts, companies, deals…",
    placeholderEnabled: true,
  },
  "file-upload": {
    ...baseFieldDefaults,
    label: "Upload a file",
    fileName: "",
  },
  "image-crop-upload": {
    ...baseFieldDefaults,
    label: "Profile photo",
    value: "",
    uploadLabel: "Browse image",
    cropButtonLabel: "Apply crop",
    changeButtonLabel: "Change photo",
    zoomLabel: "Zoom",
    viewportSize: 240,
    outputSize: 256,
    minZoom: 1,
    maxZoom: 3,
    zoomStep: 0.05,
  },
  "hidden-input": {
    ...baseFieldDefaults,
    label: "Campaign ID",
    name: "campaignId",
    value: "campaign-id-42",
    helpEnabled: true,
    help: "Hidden fields are not visible to users but submit with the form.",
  },
  "number-input": {
    ...baseFieldDefaults,
    label: "Quantity",
    value: 3,
    min: 1,
    max: 100,
    step: 1,
  },
  "password-input": {
    ...baseFieldDefaults,
    label: "Password",
    value: "hunter2!",
  },
  "range-slider": {
    ...baseFieldDefaults,
    label: "Volume",
    value: 60,
    min: 0,
    max: 100,
    step: 1,
  },
  select: {
    ...baseFieldDefaults,
    label: "Country",
    value: "Select a country",
    options: "Select a country, United Kingdom, United States, Canada",
  },
  "text-input": {
    ...baseFieldDefaults,
    label: "Full name",
    value: "Jane Cooper",
    placeholder: "Enter your full name",
    placeholderEnabled: false,
  },
  textarea: {
    ...baseFieldDefaults,
    label: "Your message",
    value: "",
    maxCharsEnabled: true,
    maxChars: 500,
    placeholder: "Type your message here...",
    placeholderEnabled: true,
  },
  "note-composer": {
    placeholder: "Add a note...",
    saveButtonLabel: "Save Note",
    showAttach: true,
    showMention: true,
    showEmoji: true,
    value: "",
  },
  "rich-text-field": {
    ...baseFieldDefaults,
    label: "Description",
    value: "<p>Describe your project goals and timeline.</p>",
    placeholder: "Write something…",
    placeholderEnabled: true,
    minHeight: 160,
  },
  "filter-select": {
    ...baseFieldDefaults,
    label: "Filters",
    value: ["Open", "High"],
  },
  "multi-select": {
    ...baseFieldDefaults,
    label: "Teams",
    value: ["Design", "Engineering"],
    options: "Design, Engineering, Marketing, Sales, Support, Operations",
  },
  "transfer-list": {
    ...baseFieldDefaults,
    label: "Office locations",
    available:
      "Amsterdam, Berlin, Copenhagen, Dublin, Helsinki, Lisbon, Madrid, Oslo, Prague, Stockholm",
    selected: ["London", "Paris"],
  },
  "password-strength-field": {
    ...baseFieldDefaults,
    label: "Create password",
    value: "Opus2026",
    showRequirements: true,
  },
  "rating-input": {
    ...baseFieldDefaults,
    label: "Satisfaction",
    value: 4,
    max: 5,
    variant: "stars",
  },
  "segmented-control": {
    ...baseFieldDefaults,
    label: "Billing cycle",
    value: "Monthly",
    options: "Monthly, Quarterly, Yearly",
  },
  "slider-range": {
    ...baseFieldDefaults,
    label: "Budget range",
    value: [20, 80],
    min: 0,
    max: 100,
    step: 5,
  },
  "phone-number-input": {
    ...baseFieldDefaults,
    label: "Mobile number",
    value: "7700 900123",
    countryCode: "GB",
  },
  "country-picker": {
    ...baseFieldDefaults,
    label: "Country",
    value: "GB",
    placeholder: "Select country…",
    placeholderEnabled: true,
    searchPlaceholder: "Search countries…",
  },
  "tree-select": {
    ...baseFieldDefaults,
    label: "Department",
    value: "frontend",
  },
  cascader: {
    ...baseFieldDefaults,
    label: "Location",
    value: ["uk", "england", "london"],
  },
  "theme-toggle": {
    mode: "flagged",
    labelPosition: "left",
    label: "Theme",
    helpEnabled: false,
    help: "Switch between light and dark appearance.",
    value: "dark",
  },
  "accent-color-picker": {
    mode: "flagged",
    labelPosition: "left",
    label: "Accent",
    helpEnabled: false,
    help: "Choose the accent colour used across the interface.",
    value: "#8f6cff",
  },
  "icon-picker": {
    mode: "stacked",
    labelPosition: "left",
    label: "Icon",
    helpEnabled: false,
    help: "Search and select an icon for this item.",
    value: "chart-column",
  },
  "emoji-picker": {
    placement: "bottom",
    searchPlaceholder: "Search emojis",
    closeOnOutside: true,
    closeOnEscape: true,
    open: false,
    lastSelected: "😀",
  },
  tooltip: {
    content: "Optional help text for this field",
    demoLabel: "Field label",
  },
  dialog: {
    actionSet: "ok-cancel",
    status: "success",
    title: "Ready to continue",
    description: "Everything looks good. Confirm to move forward.",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    open: false,
  },
  drawer: {
    title: "Filters",
    description: "Refine the current view without leaving the page.",
    content:
      "Drawers are useful for secondary workflows, navigation, filters, inspector panels, and compact forms that should stay connected to the current screen.",
    contentType: "html",
    side: "right",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeButton: true,
    footerActions: true,
    open: false,
  },
  "dropdown-menu": {
    placement: "bottom-start",
    closeOnSelect: true,
    closeOnOutside: true,
    closeOnEscape: true,
    showIcons: true,
    showDestructive: true,
    showDisabled: true,
    open: false,
  },
  "context-menu": {
    closeOnSelect: true,
    closeOnOutside: true,
    closeOnEscape: true,
    showIcons: true,
    showDestructive: true,
    showDisabled: true,
    open: false,
    targetLabel: "Right-click this area",
  },
  "command-palette": {
    open: false,
    placeholder: "Search commands…",
    emptyMessage: "No commands found.",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeOnSelect: true,
    showShortcuts: true,
    showDescriptions: true,
    showGroups: true,
    showEmptyResults: false,
  },
  modal: {
    title: "Project details",
    description: "Review supporting information without leaving the page.",
    content:
      "Modals are useful for focused workflows, longer explanatory content, previews, and forms that need more room than a confirmation dialog.",
    contentType: "html",
    size: "medium",
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    closeButton: true,
    footerActions: true,
    open: false,
  },
  popover: {
    title: "Quick actions",
    content:
      "Popovers are useful for compact contextual panels, inline settings, preview cards, and lightweight forms anchored to a trigger.",
    contentType: "html",
    placement: "bottom",
    closeOnOutside: true,
    closeOnEscape: true,
    showArrow: true,
    open: false,
  },
  alert: {
    status: "error",
    title: "There was a problem with your submission.",
    description: "Please correct the errors below and try again.",
    dismissible: true,
    iconFlagged: true,
    visible: true,
  },
  toast: {
    status: "success",
    title: "Changes saved",
    description: "Your profile was updated successfully.",
    descriptionEnabled: true,
    dismissible: true,
    autoDismissEnabled: true,
    positionVertical: "top",
    positionHorizontal: "right",
  },
  tabs: {
    activeValue: "overview",
    disabledSecond: false,
    fitted: false,
    orientation: "horizontal",
    variant: "line",
  },
  card: {
    title: "Component health",
    eyebrow: "Library status",
    content:
      "Cards are compact content containers for summaries, previews, metrics, and calls to action.",
    tone: "accent",
    density: "comfortable",
    media: true,
    footerActions: true,
  },
  "kpi-card": {
    label: "Revenue",
    value: "$128k",
    change: "8.4%",
    trend: "up",
    showChange: true,
    density: "comfortable",
    icon: "chart-column",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "stat-card": {
    label: "Customers",
    value: "3,782",
    change: "11.01%",
    trend: "up",
    showChange: true,
    density: "comfortable",
    icon: "users",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  sparkline: {
    label: "Weekly trend",
    palette: "opus",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "progress-ring": {
    label: "Quota",
    max: 100,
    previewLayout: "single",
    value: 72,
    width: "widget",
    wrapInContainer: true,
  },
  "progress-bar": {
    label: "Sprint progress",
    max: 100,
    previewLayout: "single",
    value: 64,
    width: "widget",
    wrapInContainer: true,
  },
  gauge: {
    title: "Gauge",
    subtitle: "Supporting description for the gauge",
    change: "+10%",
    changeTrend: "up",
    summary:
      "You earn $3287 today, its higher than last month. Keep up your good work!",
    density: "comfortable",
    footerMetricCount: 3,
    palette: "opus",
    trackTone: "neutral",
    valueTone: "palette",
    variant: "half",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  speedometer: {
    label: "Utilisation",
    max: 100,
    previewLayout: "single",
    value: 78,
    width: "widget",
    wrapInContainer: true,
  },
  "metric-tile": {
    label: "MRR",
    icon: "chart-line",
    previewLayout: "single",
    showSparkline: true,
    value: "$84.2k",
    width: "widget",
    wrapInContainer: true,
  },
  "pipeline-overview": {
    closingValue: "£331,000",
    title: "Pipeline Overview",
    totalLabel: "Total Pipeline Value",
    totalValue: "£2,480,000",
    period: "This Month",
    previewLayout: "single",
    proposalValue: "£621,000",
    qualificationValue: "£842,000",
    negotiationValue: "£542,000",
    stageCount: "5",
    wonValue: "£144,000",
    width: "widget",
    wrapInContainer: true,
  },
  "deals-over-time": {
    title: "Deals Over Time",
    period: "This Year",
    maxValue: "100",
    valueLabel: "Deals",
    palette: "purple",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "upcoming-tasks": {
    title: "Upcoming Tasks",
    footerLabel: "View all tasks",
    checkboxSize: "md",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "recent-activity": {
    title: "Recent Activity",
    footerLabel: "View all activity",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "top-performing-users": {
    title: "Top Performing People",
    footerLabel: "View full report",
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "user-profile": {
    name: "Carl Fearby",
    role: "Administrator",
    src: defaultUserProfilePhotoSrc,
    srcEnabled: true,
    avatarSize: "md",
    menuItemsJson: defaultUserProfileMenuItemsJson,
    photoUploadEnabled: true,
    photoUploadMenuItemId: defaultUserProfilePhotoUploadMenuItemId,
    photoUploadTitle: "Update profile photo",
    photoUploadDescription: "",
    photoUploadLabel: "Profile photo",
    photoUploadUploadLabel: "Browse image",
    photoUploadCropButtonLabel: "Apply crop",
    photoUploadChangeButtonLabel: "Change photo",
    photoUploadZoomLabel: "Zoom",
    photoUploadViewportSize: 240,
    photoUploadOutputSize: 256,
    photoUploadMinZoom: 1,
    photoUploadMaxZoom: 3,
    photoUploadZoomStep: 0.05,
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "profile-photo-upload": {
    title: "Update profile photo",
    label: "Profile photo",
    value: "",
    uploadLabel: "Browse image",
    cropButtonLabel: "Apply crop",
    changeButtonLabel: "Change photo",
    zoomLabel: "Zoom",
    viewportSize: 240,
    outputSize: 256,
    minZoom: 1,
    maxZoom: 3,
    zoomStep: 0.05,
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "404-page": {},
  "403-page": {},
  "app-setup": {
    theme: "dark",
  },
  "dashboard-list-columns": {
    layout: "row",
    previewLayout: "single",
    width: "full",
    checkboxSize: "md",
    upcomingTasksTitle: "Upcoming Tasks",
    upcomingTasksFooterLabel: "View all tasks",
    recentActivityTitle: "Recent Activity",
    recentActivityFooterLabel: "View all activity",
    topPerformingUsersTitle: "Top Performing People",
    topPerformingUsersFooterLabel: "View full report",
  },
  "notes-activity": {
    addNoteButtonLabel: "Add note",
    addNoteModalDescription:
      "Capture supporting detail, attach files, or mention teammates.",
    addNoteModalTitle: "Add a note",
    activityFooterLabel: "View all activities",
    composerPlaceholder: "Add a note...",
    density: "comfortable",
    height: "auto",
    notesFooterLabel: "View all notes",
    previewLayout: "single",
    saveButtonLabel: "Save Note",
    width: "widget",
    wrapInContainer: true,
  },
  "lab-dashboard-list-columns": {
    layout: "row",
    previewLayout: "single",
    width: "full",
    checkboxSize: "md",
    upcomingTasksTitle: "Upcoming Tasks",
    upcomingTasksFooterLabel: "View all tasks",
    recentActivityTitle: "Recent Activity",
    recentActivityFooterLabel: "View all activity",
    topPerformingUsersTitle: "Top Performing People",
    topPerformingUsersFooterLabel: "View full report",
  },
  "lab-notes-activity": {
    addNoteButtonLabel: "Add note",
    addNoteModalDescription:
      "Capture supporting detail, attach files, or mention teammates.",
    addNoteModalTitle: "Add a note",
    activityFooterLabel: "View all activities",
    composerPlaceholder: "Add a note...",
    density: "comfortable",
    height: "auto",
    notesFooterLabel: "View all notes",
    previewLayout: "single",
    saveButtonLabel: "Save Note",
    width: "widget",
    wrapInContainer: true,
  },
  "lab-sidebar": {
    side: "left",
    collapsed: false,
    density: "comfortable",
    showHeader: false,
    headerTitle: "Opus",
    showFooter: false,
    footerText: "Signed in as Alex Morgan",
    activeItem: "library",
    groupOpen: true,
    paddingBottom: false,
    paddingLeft: false,
    paddingRight: false,
    paddingTop: false,
    persistState: true,
    height: "auto",
    wrapInContainer: true,
  },
  "lab-test-layout": {
    defaultLeftWidth: 260,
    defaultRightWidth: 260,
    handleBackground: "subtle",
    handleBorderRadius: 12,
    handleHeight: "medium",
    handleMarginBlock: 12,
    height: "full",
    maxLeftWidth: 360,
    maxRightWidth: 480,
    minLeftWidth: 120,
    minRightWidth: 220,
    persist: true,
    showLeft: true,
    showRight: true,
  },
  "lab-user-profile": {
    name: "Carl Fearby",
    role: "Administrator",
    src: defaultUserProfilePhotoSrc,
    srcEnabled: true,
    avatarSize: "md",
    menuItemsJson: defaultUserProfileMenuItemsJson,
    photoUploadEnabled: true,
    photoUploadMenuItemId: defaultUserProfilePhotoUploadMenuItemId,
    photoUploadTitle: "Update profile photo",
    photoUploadDescription: "",
    photoUploadLabel: "Profile photo",
    photoUploadUploadLabel: "Browse image",
    photoUploadCropButtonLabel: "Apply crop",
    photoUploadChangeButtonLabel: "Change photo",
    photoUploadZoomLabel: "Zoom",
    photoUploadViewportSize: 240,
    photoUploadOutputSize: 256,
    photoUploadMinZoom: 1,
    photoUploadMaxZoom: 3,
    photoUploadZoomStep: 0.05,
    previewLayout: "single",
    width: "widget",
    wrapInContainer: true,
  },
  "dashboard-content-container": {
    height: "auto",
    paddingBottom: true,
    paddingLeft: true,
    paddingRight: true,
    paddingTop: true,
    previewLayout: "single",
    title: "Dashboard section",
    width: "widget",
  },
  "status-indicator": {
    label: "Systems healthy",
    previewLayout: "single",
    status: "success",
    width: "widget",
    wrapInContainer: true,
  },
  "trend-badge": {
    direction: "up",
    previewLayout: "single",
    value: "12.4%",
    width: "widget",
    wrapInContainer: true,
  },
  panel: {
    title: "Release readiness",
    description:
      "A structural panel for settings, grouped content, and page sections.",
    content:
      "Panels are broader layout primitives than cards. Use them for page sections, settings groups, and structured content blocks.",
    tone: "default",
    density: "comfortable",
    divided: true,
    bordered: true,
    footer: "Panel footer content can hold metadata, hints, or actions.",
  },
  section: {
    title: "Page layout",
    description:
      "Responsive rows and columns that stack on mobile and expand on larger screens.",
    sidebar: "none",
    columns: 3,
    gap: "md",
    stackBelow: "mobile",
    sidebarRatio: "1:2",
    sidebarTitle: "Sidebar",
    sidebarContent:
      "Navigation, filters, or supporting controls beside the main content area.",
    columnOneTitle: "Primary column",
    columnOneContent:
      "Main content area. On mobile this stacks above the secondary column.",
    columnTwoTitle: "Secondary column",
    columnTwoContent: "Supporting content beside the primary column.",
    columnThreeTitle: "Third column",
    columnThreeContent: "Additional equal-width content column on desktop.",
    columnFourTitle: "Fourth column",
    columnFourContent: "Fourth equal column on wider desktop layouts.",
    columnFiveTitle: "Fifth column",
    columnFiveContent: "Fifth equal column on wider desktop layouts.",
  },
  table: {
    caption: "Component adoption by team",
    density: "comfortable",
    striped: true,
    bordered: false,
    showCaption: true,
    showEmpty: false,
    numericColumn: true,
  },
  "data-grid": {
    caption: "Quarterly component metrics",
    density: "compact",
    striped: true,
    bordered: true,
    filterable: true,
    resizable: true,
    rowHeaderResizable: false,
    q1Q2Resizable: true,
    q1Q2SortFilter: false,
    sortable: true,
    stickyHeader: true,
    stickyFirstColumn: true,
    numericColumns: true,
    layout: "flat",
    masterDetail: false,
    virtualized: false,
    infiniteScroll: false,
  },
  skeleton: {
    animation: "shimmer",
    lines: 3,
    variant: "card",
  },
  ...chartDefaults,
  carousel: {
    initialIndex: 0,
    loop: true,
    showCaptions: true,
    showPips: true,
  },
  lightbox: {
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    showCaptions: true,
    triggerLabel: "Open lightbox",
  },
  "image-thumbnail": {
    openInLightbox: true,
    showCaption: true,
    size: "medium",
  },
  "image-gallery": {
    columns: 4,
    showCaptions: true,
    thumbnailSize: "small",
  },
  "model-viewer": {
    autoRotate: true,
    cameraControls: true,
    showCaption: true,
  },
  "model-lightbox": {
    dismissOnBackdrop: true,
    dismissOnEscape: true,
    showCaption: true,
    triggerLabel: "Open 3D asset",
  },
  "model-thumbnail": {
    openInLightbox: true,
    showCaption: true,
    size: "medium",
  },
  "model-gallery": {
    columns: 4,
    showCaptions: true,
    thumbnailSize: "small",
  },
  accordion: {
    title: "What is included?",
    content:
      "Every plan includes unlimited projects, shared workspaces, and priority email support during business hours.",
    defaultOpen: false,
    disabled: false,
  },
  "accordion-group": {
    type: "single",
    collapsible: true,
    defaultOpenFirst: true,
    itemOneTitle: "Getting started",
    itemOneContent:
      "Create a workspace, invite your team, and import existing content from Markdown or HTML.",
    itemTwoTitle: "Billing & plans",
    itemTwoContent:
      "Upgrade or downgrade at any time. Invoices are emailed on the first of each month.",
    itemThreeTitle: "Support",
    itemThreeContent:
      "Reach us through in-app chat or email support@example.com. Enterprise customers get a dedicated channel.",
  },
  "show-more": {
    content:
      "Every plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.\n\nEvery plan includes unlimited projects, shared workspaces, and priority email support during business hours.\n\nUpgrade anytime to unlock advanced analytics, custom domains, and dedicated onboarding for larger teams. Enterprise plans add SSO, audit logs, and a dedicated success manager.\n\nOur content editor supports rich formatting, embedded media, and collaborative drafts so your team can publish faster without sacrificing quality. Templates, reusable blocks, and version history keep long-form pages manageable as your library grows.\n\nNeed help getting started? Browse the onboarding guide, join a live workshop, or reach out to support and we will walk through your first project setup together.",
    maxLines: 3,
    showMoreLabel: "Show more",
    showLessLabel: "Show less",
    defaultExpanded: false,
  },
  "empty-state": {
    title: "No components yet",
    description:
      "Create your first component to start building your library and sharing patterns across teams.",
    density: "comfortable",
    showIcon: true,
    icon: "inbox",
    primaryAction: true,
    primaryActionLabel: "Create component",
    secondaryAction: true,
    secondaryActionLabel: "Browse templates",
  },
  badge: {
    label: "In review",
    tone: "accent",
    variant: "soft",
    size: "md",
    dot: true,
  },
  avatar: {
    name: "Alex Morgan",
    size: "md",
    shape: "circle",
    srcEnabled: false,
    src: "",
  },
  "avatar-group": {
    size: "md",
    max: 3,
  },
  list: {
    density: "comfortable",
    ordered: false,
    showIcons: true,
  },
  "description-list": {
    layout: "stacked",
  },
  divider: {
    orientation: "horizontal",
    tone: "default",
    labelEnabled: true,
    label: "Or continue",
  },
  "content-timeline": {
    includeGroups: false,
    includeStatus: true,
    includeTags: true,
    rowStyles: ["avatar", "avatar", "status"],
  },
  "tree-view": {
    expandRoots: true,
  },
  "masonry-grid": {
    columns: 3,
    gap: 12,
  },
  "property-grid": {
    copyable: true,
    bordered: false,
  },
  stack: {
    direction: "column",
    gap: 12,
    wrap: false,
  },
  columns: {
    direction: "row",
    columns: 3,
    gap: 16,
  },
  grid: {
    columns: 3,
    gap: 12,
  },
  splitter: {
    orientation: "horizontal",
    defaultSize: 40,
  },
  "resize-handle": {
    background: "subtle",
    height: "medium",
    orientation: "vertical",
  },
  "resizable-panel": {
    defaultWidth: 320,
    defaultHeight: 200,
  },
  "dock-layout": {
    showLeft: true,
    showRight: true,
    showTop: true,
    showBottom: true,
  },
  "three-pane-layout": {
    defaultLeftWidth: 220,
    defaultRightWidth: 260,
    handleBackground: "subtle",
    handleBorderRadius: 0,
    handleHeight: "medium",
    handleMarginBlock: 0,
    height: "full",
    maxLeftWidth: 420,
    maxRightWidth: 460,
    minLeftWidth: 140,
    minRightWidth: 160,
    persist: true,
    showLeft: true,
    showRight: true,
  },
  "scroll-area": {
    autoHide: true,
    maxHeight: 180,
    orientation: "vertical",
    thickness: 12,
  },
  "custom-scrollbar": {
    autoHide: true,
    horizontalThumbShape: "round",
    horizontalTrackShape: "round",
    maxHeight: 220,
    minThumbSize: 32,
    orientation: "vertical",
    thickness: 12,
    verticalThumbShape: "round",
    verticalTrackShape: "round",
  },
  "aspect-ratio": {
    ratio: "16 / 9",
  },
  container: {
    size: "md",
    padded: true,
  },
  spacer: {
    axis: "y",
    size: 24,
    flex: false,
  },
  breadcrumb: {
    separator: "/",
  },
  pagination: {
    page: 2,
    pageCount: 8,
  },
  "page-header": {
    showBreadcrumbs: true,
    showActions: true,
  },
  toolbar: {
    dense: false,
  },
  "bottom-navigation": {
    value: "home",
  },
  "navigation-rail": {
    collapsed: false,
    value: "inbox",
  },
  "split-button": {
    variant: "primary",
  },
  fab: {
    extended: false,
    size: "md",
  },
  tile: {
    icon: "user-plus",
    label: "New Lead",
    tone: "purple",
  },
  tiles: {
    layout: "fill",
  },
  "stat-tile": {
    label: "Total Contacts",
    value: "2,543",
    trendValue: "12.5%",
    trend: "up",
    comparison: "vs last 30 days",
    icon: "user",
    tone: "blue",
  },
  "stat-tiles": {
    layout: "fill",
  },
  "property-inspector": {
    searchable: true,
  },
  "filter-builder": {
    seedCount: 2,
  },
  "query-builder": {
    combinator: "and",
  },
  "rule-builder": {
    showDisabled: true,
  },
  "permissions-matrix": {
    compact: false,
  },
  "dual-list-builder": {
    selectedCount: 2,
  },
  scheduler: {
    startHour: 9,
    endHour: 17,
  },
  "kanban-board": {
    interactive: true,
  },
  calendar: {
    openDayOnSelect: true,
    showEvents: true,
    showMonthYearPicker: true,
  },
  "resource-planner": {
    startHour: 8,
    endHour: 17,
  },
  "json-viewer": {
    collapsedDepth: 1,
  },
  statistic: {
    label: "Monthly active users",
    value: "24.8",
    prefix: "",
    suffix: "k",
    trendEnabled: true,
    trend: "up",
    trendLabel: "12.4% vs last month",
  },
  icon: {
    name: "star",
    size: "md",
    tone: "accent",
    labelEnabled: true,
    label: "Favourite",
  },
  "icon-badge": {
    iconName: "bell",
    count: 8,
    max: 99,
    size: "md",
    tone: "muted",
    urgency: "standard",
    label: "Notifications",
    showZero: false,
    showToolbarDemo: true,
  },
  spinner: {
    size: "md",
    tone: "accent",
    label: "Loading",
  },
  clock: {
    showAnalog: true,
    showDate: true,
    showDigital: true,
    size: "md",
  },
  portal: {
    disabled: false,
    message: "Rendered through a portal",
  },
  "portal-host": {
    hostId: "opus-demo-portal-host",
    message: "Hosted portal content",
  },
  "visually-hidden": {
    text: "Screen reader only announcement",
    showHint: true,
  },
  "focus-trap": {
    active: true,
  },
  "keyboard-shortcut": {
    keys: "⌘ K",
    size: "md",
  },
  "hotkey-manager": {
    enabled: true,
    key: "k",
  },
  "copy-button": {
    value: "npm install opus-react",
    label: "Copy",
    copiedLabel: "Copied",
  },
  clipboard: {
    value: "Hello from Clipboard",
  },
  "theme-provider": {
    theme: "dark",
  },
  "theme-switcher": {
    theme: "dark",
    label: "Theme",
  },
  "resize-observer": {
    hint: "Resize the box",
  },
  "intersection-observer": {
    threshold: 0.4,
  },
  sidebar: {
    side: "left",
    collapsed: false,
    density: "comfortable",
    showHeader: false,
    headerTitle: "Opus",
    showFooter: false,
    footerText: "Signed in as Alex Morgan",
    activeItem: "library",
    groupOpen: true,
    paddingBottom: false,
    paddingLeft: false,
    paddingRight: false,
    paddingTop: false,
    persistState: true,
    height: "auto",
    wrapInContainer: false,
  },
  "mega-menu": {
    closeOnEscape: true,
    closeOnOutside: true,
    columnCount: 2,
    density: "comfortable",
    featured: true,
    featuredActionLabel: "Explore library",
    featuredDescription:
      "Browse production-ready components, patterns, and implementation notes from one navigation surface.",
    featuredEyebrow: "Featured",
    featuredTitle: "Build faster with Opus",
    itemsPerColumn: 3,
  },
  "top-navigation": {
    activeMenu: "none",
    closeOnEscape: true,
    closeOnOutside: true,
    closeOnSelect: true,
    density: "comfortable",
    showShortcuts: true,
  },
};

export function getDefaultSettings<S extends ControlSlug>(
  slug: S,
): ControlSettingsBySlug[S] {
  return structuredClone(defaultSettings[slug]);
}
