import type { ComponentCategory, ControlDefinition, ControlSlug } from "./types";
import { formsControlOrder } from "./types";
import { buildersCatalog } from "./buildersCatalog";
import { chartCatalog } from "./chartCatalog";
import { dashboardCatalog } from "./dashboardCatalog";
import { labsCatalog } from "./labsCatalog";
import { systemCatalog } from "./systemCatalog";
import { layoutCatalog } from "./layoutCatalog";
import { navigationExtrasCatalog } from "./navigationExtrasCatalog";
import { tilesCatalog } from "./tilesCatalog";

export const componentCategories: { id: ComponentCategory; label: string }[] = [
  { id: "content", label: "Content" },
  { id: "forms", label: "Forms" },
  { id: "graphs", label: "Graphs" },
  { id: "labs", label: "Labs" },
  { id: "overlays", label: "Overlays" },
  { id: "system", label: "System" },
].sort((a, b) => a.label.localeCompare(b.label)) as { id: ComponentCategory; label: string }[];

export const categoryDescriptions: Record<ComponentCategory, string> = {
  content:
    "Expandable sections, grouped accordions, alerts, navigation menus, empty states, sidebars, and show more / show less controls.",
  forms: "Inputs, selectors, toggles, buttons, and every field pattern used across Opus forms.",
  graphs: "Charts and visualisations for comparing, trending, segmenting, and exploring metric data.",
  labs: "Experimental compositions that combine multiple library components into ready-made patterns.",
  overlays: "Tooltips, command palettes, modals, drawers, and toast notifications for contextual help and feedback.",
  system: "Application shells, setup boilerplates, and route-level pages such as error and access-denied states.",
};

const graphControls: ControlDefinition[] = chartCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "graphs",
  componentName: "Chart",
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: ["components/Chart/Chart.tsx", "components/Chart/Chart.module.css", "components/Chart/SpecializedCharts.tsx"],
  usesFieldShell: false,
}));

const buildersControls: ControlDefinition[] = buildersCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "content",
  componentName: entry.componentName,
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const layoutControls: ControlDefinition[] = layoutCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "content",
  componentName: entry.componentName,
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const navigationExtrasControls: ControlDefinition[] = navigationExtrasCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "content",
  componentName: entry.componentName,
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const tilesControls: ControlDefinition[] = tilesCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "content",
  componentName: entry.componentName,
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const labControls: ControlDefinition[] = labsCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "labs",
  componentName: entry.componentName,
  description: entry.description,
  compositionParts: [...entry.compositionParts],
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const systemControls: ControlDefinition[] = systemCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "system",
  componentName: entry.componentName,
  description: entry.description,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const dashboardControls: ControlDefinition[] = dashboardCatalog.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  category: "content",
  componentName: entry.componentName,
  description: entry.description,
  navigationGroup: entry.navigationGroup,
  sourceFiles: entry.sourceFiles,
  usesFieldShell: false,
}));

const formsControls: Record<(typeof formsControlOrder)[number], ControlDefinition> = {
  button: {
    slug: "button",
    title: "Button",
    category: "forms",
    componentName: "Button",
    description: "Standalone button with multiple style variants.",
    sourceFiles: ["components/fields/Button/Button.tsx", "components/fields/Button/Button.module.css"],
    usesFieldShell: false,
  },
  "submit-button": {
    slug: "submit-button",
    title: "Submit button",
    category: "forms",
    componentName: "Button",
    description: "Primary form submission button with type=\"submit\".",
    sourceFiles: ["components/fields/Button/Button.tsx", "components/fields/Button/Button.module.css"],
    usesFieldShell: false,
  },
  "reset-button": {
    slug: "reset-button",
    title: "Reset button",
    category: "forms",
    componentName: "Button",
    description: "Form reset button with type=\"reset\".",
    sourceFiles: ["components/fields/Button/Button.tsx", "components/fields/Button/Button.module.css"],
    usesFieldShell: false,
  },
  checkbox: {
    slug: "checkbox",
    title: "Checkbox",
    category: "forms",
    componentName: "CheckboxField",
    description: "Boolean checkbox with round or square shape variants.",
    sourceFiles: ["components/fields/CheckboxField/CheckboxField.tsx", "components/fields/CheckboxField/CheckboxField.module.css"],
    usesFieldShell: true,
  },
  switch: {
    slug: "switch",
    title: "Switch",
    category: "forms",
    componentName: "SwitchField",
    description: "Toggle switch for on/off settings.",
    sourceFiles: ["components/fields/SwitchField/SwitchField.tsx", "components/fields/SwitchField/SwitchField.module.css"],
    usesFieldShell: true,
  },
  "radio-group": {
    slug: "radio-group",
    title: "Radio group",
    category: "forms",
    componentName: "RadioGroup",
    description: "Grouped radio options with shared selection state and optional per-option errors.",
    sourceFiles: ["components/fields/RadioGroup/RadioGroup.tsx", "components/fields/RadioGroup/RadioGroup.module.css"],
    usesFieldShell: true,
  },
  "chip-input": {
    slug: "chip-input",
    title: "Chip input",
    category: "forms",
    componentName: "ChipInput",
    description: "Tokenised input that turns typed values into removable chips.",
    sourceFiles: [
      "components/fields/ChipInputField/ChipInputField.tsx",
      "components/fields/ChipInputField/ChipInputField.module.css",
    ],
    usesFieldShell: true,
  },
  "color-picker": {
    slug: "color-picker",
    title: "Colour picker",
    category: "forms",
    componentName: "ColorField",
    description: "Colour input with swatch and hex value display.",
    sourceFiles: ["components/fields/ColorField/ColorField.tsx", "components/fields/ColorField/ColorField.module.css"],
    usesFieldShell: true,
  },
  "date-picker": {
    slug: "date-picker",
    title: "Date picker",
    category: "forms",
    componentName: "DateField",
    description: "Native date input wrapped in FieldShell.",
    sourceFiles: ["components/fields/DateField/DateField.tsx", "components/fields/DateField/DateField.module.css"],
    usesFieldShell: true,
  },
  "time-picker": {
    slug: "time-picker",
    title: "Time picker",
    category: "forms",
    componentName: "DateField",
    description: "Native time input with type=\"time\".",
    sourceFiles: ["components/fields/DateField/DateField.tsx", "components/fields/DateField/DateField.module.css"],
    usesFieldShell: true,
  },
  "datetime-picker": {
    slug: "datetime-picker",
    title: "Date/time picker",
    category: "forms",
    componentName: "DateField",
    description: "Native date and time input with type=\"datetime-local\".",
    sourceFiles: ["components/fields/DateField/DateField.tsx", "components/fields/DateField/DateField.module.css"],
    usesFieldShell: true,
  },
  "month-picker": {
    slug: "month-picker",
    title: "Month picker",
    category: "forms",
    componentName: "DateField",
    description: "Native month input with type=\"month\".",
    sourceFiles: ["components/fields/DateField/DateField.tsx", "components/fields/DateField/DateField.module.css"],
    usesFieldShell: true,
  },
  "week-picker": {
    slug: "week-picker",
    title: "Week picker",
    category: "forms",
    componentName: "DateField",
    description: "Native week input with type=\"week\".",
    sourceFiles: ["components/fields/DateField/DateField.tsx", "components/fields/DateField/DateField.module.css"],
    usesFieldShell: true,
  },
  "email-input": {
    slug: "email-input",
    title: "Email input",
    category: "forms",
    componentName: "TextField",
    description: "Email variant of TextField with type=\"email\".",
    sourceFiles: ["components/fields/TextField/TextField.tsx", "components/fields/TextField/TextField.module.css"],
    usesFieldShell: true,
  },
  "url-input": {
    slug: "url-input",
    title: "URL input",
    category: "forms",
    componentName: "TextField",
    description: "URL variant of TextField with type=\"url\".",
    sourceFiles: ["components/fields/TextField/TextField.tsx", "components/fields/TextField/TextField.module.css"],
    usesFieldShell: true,
  },
  "search-input": {
    slug: "search-input",
    title: "Search input",
    category: "forms",
    componentName: "TextField",
    description: "Search variant of TextField with type=\"search\".",
    sourceFiles: ["components/fields/TextField/TextField.tsx", "components/fields/TextField/TextField.module.css"],
    usesFieldShell: true,
  },
  "file-upload": {
    slug: "file-upload",
    title: "File upload",
    category: "forms",
    componentName: "FileField",
    description: "File picker with drag-and-drop styled drop zone.",
    sourceFiles: ["components/fields/FileField/FileField.tsx", "components/fields/FileField/FileField.module.css"],
    usesFieldShell: true,
  },
  "image-crop-upload": {
    slug: "image-crop-upload",
    title: "Image crop upload",
    category: "forms",
    componentName: "ImageCropUploadField",
    description:
      "Profile photo uploader with circular mask, drag-to-position, zoom controls, and canvas crop before upload.",
    sourceFiles: [
      "components/fields/ImageCropUploadField/ImageCropUploadField.tsx",
      "components/fields/ImageCropUploadField/ImageCropUploadField.module.css",
      "components/fields/ImageCropUploadField/cropCircularImage.ts",
    ],
    usesFieldShell: true,
  },
  "hidden-input": {
    slug: "hidden-input",
    title: "Hidden input",
    category: "forms",
    componentName: "HiddenField",
    description: "Hidden form value that submits with the form without visible UI.",
    sourceFiles: ["components/fields/HiddenField/HiddenField.tsx", "components/fields/HiddenField/HiddenField.module.css"],
    usesFieldShell: true,
  },
  "number-input": {
    slug: "number-input",
    title: "Number input",
    category: "forms",
    componentName: "NumberField",
    description: "Number stepper with increment/decrement controls.",
    sourceFiles: ["components/fields/NumberField/NumberField.tsx", "components/fields/NumberField/NumberField.module.css"],
    usesFieldShell: true,
  },
  "password-input": {
    slug: "password-input",
    title: "Password input",
    category: "forms",
    componentName: "TextField",
    description: "Password variant of TextField with type=\"password\".",
    sourceFiles: ["components/fields/TextField/TextField.tsx", "components/fields/TextField/TextField.module.css"],
    usesFieldShell: true,
  },
  "range-slider": {
    slug: "range-slider",
    title: "Range slider",
    category: "forms",
    componentName: "RangeField",
    description: "Slider input with percentage display.",
    sourceFiles: ["components/fields/RangeField/RangeField.tsx", "components/fields/RangeField/RangeField.module.css"],
    usesFieldShell: true,
  },
  select: {
    slug: "select",
    title: "Select",
    category: "forms",
    componentName: "SelectField",
    description: "Dropdown select with a list of string options.",
    sourceFiles: ["components/fields/SelectField/SelectField.tsx", "components/fields/SelectField/SelectField.module.css"],
    usesFieldShell: true,
  },
  "text-input": {
    slug: "text-input",
    title: "Text input",
    category: "forms",
    componentName: "TextField",
    description: "Single-line text input with optional placeholder, help text, and validation error.",
    sourceFiles: ["components/fields/TextField/TextField.tsx", "components/fields/TextField/TextField.module.css"],
    usesFieldShell: true,
  },
  textarea: {
    slug: "textarea",
    title: "Textarea",
    category: "forms",
    componentName: "TextAreaField",
    description: "Multi-line text input with optional character limit and count display.",
    sourceFiles: ["components/fields/TextAreaField/TextAreaField.tsx", "components/fields/TextAreaField/TextAreaField.module.css"],
    usesFieldShell: true,
  },
  "note-composer": {
    slug: "note-composer",
    title: "Note composer",
    category: "forms",
    componentName: "NoteComposer",
    description: "Inset note entry box with attachment, mention, emoji picker, and save action.",
    sourceFiles: [
      "components/NoteComposer/NoteComposer.tsx",
      "components/NoteComposer/NoteComposer.module.css",
      "components/EmojiPicker/EmojiPicker.tsx",
      "components/EmojiPicker/EmojiPicker.module.css",
    ],
    usesFieldShell: false,
  },
  "rich-text-field": {
    slug: "rich-text-field",
    title: "Rich text field",
    category: "forms",
    componentName: "RichTextField",
    description: "WYSIWYG editor with an icon toolbar, headings, lists, alignment, links, and live active-state buttons.",
    sourceFiles: [
      "components/fields/RichTextField/RichTextField.tsx",
      "components/fields/RichTextField/RichTextField.module.css",
    ],
    usesFieldShell: true,
  },
  "filter-select": {
    slug: "filter-select",
    title: "Filter select",
    category: "forms",
    componentName: "FilterSelectField",
    description: "Dropdown menu with checkboxes, search, groups, and apply/reset actions.",
    sourceFiles: [
      "components/fields/FilterSelectField/FilterSelectField.tsx",
      "components/fields/FilterSelectField/FilterSelectField.module.css",
    ],
    usesFieldShell: true,
  },
  "multi-select": {
    slug: "multi-select",
    title: "Multi select",
    category: "forms",
    componentName: "MultiSelectField",
    description: "Select multiple fixed options from a dropdown checklist.",
    sourceFiles: [
      "components/fields/MultiSelectField/MultiSelectField.tsx",
      "components/fields/MultiSelectField/MultiSelectField.module.css",
    ],
    usesFieldShell: true,
  },
  "transfer-list": {
    slug: "transfer-list",
    title: "Transfer list",
    category: "forms",
    componentName: "TransferListField",
    description: "Move items between available and selected lists with shuttle controls.",
    sourceFiles: [
      "components/fields/TransferListField/TransferListField.tsx",
      "components/fields/TransferListField/TransferListField.module.css",
    ],
    usesFieldShell: true,
  },
  "password-strength-field": {
    slug: "password-strength-field",
    title: "Password strength field",
    category: "forms",
    componentName: "PasswordStrengthField",
    description: "Password input with strength meter and requirement checklist.",
    sourceFiles: [
      "components/fields/PasswordStrengthField/PasswordStrengthField.tsx",
      "components/fields/PasswordStrengthField/PasswordStrengthField.module.css",
    ],
    usesFieldShell: true,
  },
  "rating-input": {
    slug: "rating-input",
    title: "Rating input",
    category: "forms",
    componentName: "RatingField",
    description: "Rate with stars, hearts, or a numeric scale.",
    sourceFiles: [
      "components/fields/RatingField/RatingField.tsx",
      "components/fields/RatingField/RatingField.module.css",
    ],
    usesFieldShell: true,
  },
  "segmented-control": {
    slug: "segmented-control",
    title: "Segmented control",
    category: "forms",
    componentName: "SegmentedControlField",
    description: "Button-like radio group for compact single-choice selection.",
    sourceFiles: [
      "components/fields/SegmentedControlField/SegmentedControlField.tsx",
      "components/fields/SegmentedControlField/SegmentedControlField.module.css",
    ],
    usesFieldShell: true,
  },
  "slider-range": {
    slug: "slider-range",
    title: "Slider range",
    category: "forms",
    componentName: "SliderRangeField",
    description: "Dual-thumb range slider for selecting a minimum and maximum value.",
    sourceFiles: [
      "components/fields/SliderRangeField/SliderRangeField.tsx",
      "components/fields/SliderRangeField/SliderRangeField.module.css",
    ],
    usesFieldShell: true,
  },
  "phone-number-input": {
    slug: "phone-number-input",
    title: "Phone number input",
    category: "forms",
    componentName: "PhoneNumberField",
    description: "Country selector with formatted telephone number input.",
    sourceFiles: [
      "components/fields/PhoneNumberField/PhoneNumberField.tsx",
      "components/fields/PhoneNumberField/PhoneNumberField.module.css",
    ],
    usesFieldShell: true,
  },
  "country-picker": {
    slug: "country-picker",
    title: "Country picker",
    category: "forms",
    componentName: "CountryPickerField",
    description: "Searchable dropdown for selecting a country with flag icons.",
    sourceFiles: [
      "components/fields/CountryPickerField/CountryPickerField.tsx",
      "components/fields/CountryPickerField/CountryPickerField.module.css",
    ],
    usesFieldShell: true,
  },
  "tree-select": {
    slug: "tree-select",
    title: "Tree select",
    category: "forms",
    componentName: "TreeSelectField",
    description: "Dropdown for hierarchical options such as teams, folders, or departments.",
    sourceFiles: [
      "components/fields/TreeSelectField/TreeSelectField.tsx",
      "components/fields/TreeSelectField/TreeSelectField.module.css",
    ],
    usesFieldShell: true,
  },
  cascader: {
    slug: "cascader",
    title: "Cascader",
    category: "forms",
    componentName: "CascaderField",
    description: "Multi-level dropdown for country → region → city style selection.",
    sourceFiles: [
      "components/fields/CascaderField/CascaderField.tsx",
      "components/fields/CascaderField/CascaderField.module.css",
    ],
    usesFieldShell: true,
  },
};

export const controls: ControlDefinition[] = [
  ...formsControlOrder.map((slug) => formsControls[slug]),
  ...graphControls,
  {
    slug: "theme-toggle",
    title: "Theme toggle",
    category: "forms",
    componentName: "ThemeToggleField",
    description: "Flagged light/dark theme switch with sun and moon icons.",
    sourceFiles: [
      "components/fields/ThemeToggleField/ThemeToggleField.tsx",
      "components/fields/ThemeToggleField/ThemeToggleField.module.css",
    ],
    usesFieldShell: true,
  },
  {
    slug: "accent-color-picker",
    title: "Accent colour picker",
    category: "forms",
    componentName: "AccentColorPicker",
    description: "Preset accent colour swatches for branding and theme customisation.",
    sourceFiles: [
      "components/AccentColorPicker/AccentColorPicker.tsx",
      "components/AccentColorPicker/AccentColorPicker.module.css",
    ],
    usesFieldShell: true,
  },
  {
    slug: "icon-picker",
    title: "Icon picker",
    category: "forms",
    componentName: "IconPicker",
    description: "Searchable Font Awesome icon picker with frosted icon badges.",
    sourceFiles: ["components/IconPicker/IconPicker.tsx", "components/IconPicker/IconPicker.module.css"],
    usesFieldShell: true,
  },
  {
    slug: "emoji-picker",
    title: "Emoji picker",
    category: "forms",
    componentName: "EmojiPicker",
    description: "Categorized emoji picker with search, opened as a popover from a trigger button.",
    sourceFiles: [
      "components/EmojiPicker/EmojiPicker.tsx",
      "components/EmojiPicker/EmojiPicker.module.css",
      "lib/emojiCatalog.ts",
      "lib/emojiCatalog.types.ts",
      "lib/emojiCatalog.generated.ts",
      "lib/emojiRecentStorage.ts",
    ],
    usesFieldShell: false,
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    category: "overlays",
    componentName: "Tooltip",
    description: "Info icon that reveals help text in a popup on hover or click.",
    sourceFiles: ["components/Tooltip/Tooltip.tsx", "components/Tooltip/Tooltip.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "dialog",
    title: "Dialog",
    category: "overlays",
    componentName: "Dialog",
    description: "Modal confirmation dialog with OK, OK/cancel, yes/no, and destructive delete action sets.",
    sourceFiles: ["components/Dialog/Dialog.tsx", "components/Dialog/Dialog.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "drawer",
    title: "Drawer",
    category: "overlays",
    componentName: "Drawer",
    description: "Edge-attached overlay for filters, inspectors, navigation, and compact workflows.",
    sourceFiles: ["components/Drawer/Drawer.tsx", "components/Drawer/Drawer.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "dropdown-menu",
    title: "Dropdown menu",
    category: "content",
    componentName: "DropdownMenu",
    description: "Anchored action menu with selectable, disabled, checked, and destructive item states.",
    navigationGroup: "Navigation",
    sourceFiles: ["components/DropdownMenu/DropdownMenu.tsx", "components/DropdownMenu/DropdownMenu.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "context-menu",
    title: "Context menu",
    category: "overlays",
    componentName: "ContextMenuProvider",
    description: "Right-click action menu positioned at the pointer with the same item states as dropdown menus.",
    sourceFiles: [
      "components/ContextMenu/ContextMenuProvider.tsx",
      "components/ContextMenu/ContextMenu.module.css",
    ],
    usesFieldShell: false,
  },
  {
    slug: "command-palette",
    title: "Command palette",
    category: "overlays",
    componentName: "CommandPalette",
    description: "Keyboard-first command launcher with search, grouped results, shortcuts, and empty states.",
    sourceFiles: ["components/CommandPalette/CommandPalette.tsx", "components/CommandPalette/CommandPalette.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "modal",
    title: "Modal",
    category: "overlays",
    componentName: "Modal",
    description: "General-purpose overlay panel for longer content, forms, previews, and multi-step workflows.",
    sourceFiles: ["components/Modal/Modal.tsx", "components/Modal/Modal.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "popover",
    title: "Popover",
    category: "overlays",
    componentName: "Popover",
    description: "Anchored floating panel for contextual content, quick actions, and compact forms.",
    sourceFiles: ["components/Popover/Popover.tsx", "components/Popover/Popover.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "alert",
    title: "Alert",
    category: "content",
    componentName: "Alert",
    description: "Dismissible banner for form submission feedback with error, success, warning, and info states.",
    sourceFiles: ["components/Alert/Alert.tsx", "components/Alert/Alert.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "toast",
    title: "Toast",
    category: "overlays",
    componentName: "Toast",
    description: "Compact floating notification with status variants, rendered via ToastProvider and useToast().",
    sourceFiles: [
      "components/Toast/Toast.tsx",
      "components/Toast/Toast.module.css",
      "components/ToastProvider/ToastProvider.tsx",
      "components/ToastProvider/ToastProvider.module.css",
    ],
    usesFieldShell: false,
  },
  {
    slug: "tabs",
    title: "Tabs",
    category: "content",
    componentName: "Tabs",
    description: "Tabbed content navigation with horizontal or vertical orientation and disabled tab support.",
    navigationGroup: "Navigation",
    sourceFiles: ["components/Tabs/Tabs.tsx", "components/Tabs/Tabs.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "card",
    title: "Card",
    category: "content",
    componentName: "Card",
    description: "Compact surface for summaries, previews, metrics, media, and calls to action.",
    sourceFiles: ["components/Card/Card.tsx", "components/Card/Card.module.css"],
    usesFieldShell: false,
  },
  ...dashboardControls,
  ...labControls,
  ...systemControls,
  ...buildersControls,
  ...layoutControls,
  ...navigationExtrasControls,
  ...tilesControls,
  {
    slug: "panel",
    title: "Panel",
    category: "content",
    componentName: "Panel",
    description: "Structured page section for settings groups, content blocks, and layout regions.",
    sourceFiles: ["components/Panel/Panel.tsx", "components/Panel/Panel.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "section",
    title: "Section",
    category: "content",
    componentName: "Section",
    description: "Responsive page layout with rows, columns, presets, and mobile-to-desktop breakpoints.",
    sourceFiles: [
      "components/Section/Section.tsx",
      "components/Section/Section.module.css",
      "lib/layout/sectionLayout.ts",
    ],
    usesFieldShell: false,
  },
  {
    slug: "table",
    title: "Table",
    category: "content",
    componentName: "Table",
    description: "Responsive data table with caption, density, striped, bordered, numeric, and empty states.",
    navigationGroup: "Data",
    sourceFiles: ["components/Table/Table.tsx", "components/Table/Table.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "data-grid",
    title: "Data grid",
    category: "content",
    componentName: "DataGrid",
    description: "Scrollable data grid with fixed top header and fixed left row header.",
    navigationGroup: "Data",
    sourceFiles: ["components/DataGrid/DataGrid.tsx", "components/DataGrid/DataGrid.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    category: "content",
    componentName: "Skeleton",
    description: "Loading placeholder with text, card, avatar, and table variants.",
    sourceFiles: ["components/Skeleton/Skeleton.tsx", "components/Skeleton/Skeleton.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "carousel",
    title: "Carousel",
    category: "content",
    componentName: "Carousel",
    description: "Image carousel with previous and next controls, captions, and active slide pips.",
    navigationGroup: "Images",
    sourceFiles: ["components/Carousel/Carousel.tsx", "components/Carousel/Carousel.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "lightbox",
    title: "Lightbox",
    category: "content",
    componentName: "Lightbox",
    description: "Single-image overlay viewer with caption and dismiss options.",
    navigationGroup: "Images",
    sourceFiles: ["components/Lightbox/Lightbox.tsx", "components/Lightbox/Lightbox.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "image-thumbnail",
    title: "Image thumbnail",
    category: "content",
    componentName: "ImageThumbnail",
    description: "Single image thumbnail with optional caption and lightbox preview.",
    navigationGroup: "Images",
    sourceFiles: ["components/ImageThumbnail/ImageThumbnail.tsx", "components/ImageThumbnail/ImageThumbnail.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "image-gallery",
    title: "Image gallery",
    category: "content",
    componentName: "ImageGallery",
    description: "Grid of image thumbnails that open individual images in Lightbox.",
    navigationGroup: "Images",
    sourceFiles: [
      "components/ImageGallery/ImageGallery.tsx",
      "components/ImageGallery/ImageGallery.module.css",
      "components/ImageThumbnail/ImageThumbnail.tsx",
      "components/ImageThumbnail/ImageThumbnail.module.css",
      "components/Lightbox/Lightbox.tsx",
      "components/Lightbox/Lightbox.module.css",
    ],
    usesFieldShell: false,
  },
  {
    slug: "model-viewer",
    title: "3D asset viewer",
    category: "content",
    componentName: "ModelViewer",
    description: "Interactive GLB model preview with orbit controls, lighting, and caption metadata.",
    navigationGroup: "3D Assets",
    sourceFiles: ["components/ModelViewer/ModelViewer.tsx", "components/ModelViewer/ModelViewer.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "model-lightbox",
    title: "3D asset lightbox",
    category: "content",
    componentName: "ModelLightbox",
    description: "Full-screen 3D model overlay for inspecting a single asset.",
    navigationGroup: "3D Assets",
    sourceFiles: [
      "components/ModelLightbox/ModelLightbox.tsx",
      "components/ModelLightbox/ModelLightbox.module.css",
      "components/ModelViewer/ModelViewer.tsx",
      "components/ModelViewer/ModelViewer.module.css",
    ],
    usesFieldShell: false,
  },
  {
    slug: "model-thumbnail",
    title: "3D asset thumbnail",
    category: "content",
    componentName: "ModelThumbnail",
    description: "Compact 3D model preview that can open a full model lightbox.",
    navigationGroup: "3D Assets",
    sourceFiles: [
      "components/ModelThumbnail/ModelThumbnail.tsx",
      "components/ModelThumbnail/ModelThumbnail.module.css",
      "components/ModelLightbox/ModelLightbox.tsx",
      "components/ModelViewer/ModelViewer.tsx",
    ],
    usesFieldShell: false,
  },
  {
    slug: "model-gallery",
    title: "3D asset gallery",
    category: "content",
    componentName: "ModelGallery",
    description: "Grid of 3D asset thumbnails that open individual model lightboxes.",
    navigationGroup: "3D Assets",
    sourceFiles: [
      "components/ModelGallery/ModelGallery.tsx",
      "components/ModelGallery/ModelGallery.module.css",
      "components/ModelThumbnail/ModelThumbnail.tsx",
      "components/ModelLightbox/ModelLightbox.tsx",
      "components/ModelViewer/ModelViewer.tsx",
    ],
    usesFieldShell: false,
  },
  {
    slug: "accordion",
    title: "Accordion",
    category: "content",
    componentName: "Accordion",
    description: "Expandable section with a trigger and collapsible panel for FAQs, settings, and page content.",
    navigationGroup: "Accordion",
    sourceFiles: ["components/Accordion/Accordion.tsx", "components/Accordion/Accordion.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "accordion-group",
    title: "Accordion group",
    category: "content",
    componentName: "AccordionGroup",
    description: "Coordinates multiple accordion items with single or multiple expand modes.",
    navigationGroup: "Accordion",
    sourceFiles: [
      "components/AccordionGroup/AccordionGroup.tsx",
      "components/AccordionGroup/AccordionGroup.module.css",
      "components/Accordion/Accordion.tsx",
      "components/Accordion/Accordion.module.css",
    ],
    usesFieldShell: false,
  },
  {
    slug: "show-more",
    title: "Show more",
    category: "content",
    componentName: "ShowMore",
    description: "Truncates long content with a line clamp and an expandable show more / show less control.",
    sourceFiles: ["components/ShowMore/ShowMore.tsx", "components/ShowMore/ShowMore.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "empty-state",
    title: "Empty state",
    category: "content",
    componentName: "EmptyState",
    description: "Centre-aligned placeholder for empty lists, search results, and first-use screens.",
    sourceFiles: ["components/EmptyState/EmptyState.tsx", "components/EmptyState/EmptyState.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "badge",
    title: "Badge",
    category: "content",
    componentName: "Badge",
    description: "Compact status and category labels with tone, variant, and optional status dot.",
    sourceFiles: ["components/Badge/Badge.tsx", "components/Badge/Badge.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "avatar",
    title: "Avatar",
    category: "content",
    componentName: "Avatar",
    description: "User or entity image with initials fallback, size, and shape options.",
    sourceFiles: ["components/Avatar/Avatar.tsx", "components/Avatar/Avatar.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "avatar-group",
    title: "Avatar group",
    category: "content",
    componentName: "AvatarGroup",
    description: "Stacked avatars with overflow count for teams and collaborators.",
    sourceFiles: ["components/AvatarGroup/AvatarGroup.tsx", "components/AvatarGroup/AvatarGroup.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "list",
    title: "List",
    category: "content",
    componentName: "List",
    description: "Structured list of titles, descriptions, and optional meta or icons.",
    sourceFiles: ["components/List/List.tsx", "components/List/List.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "description-list",
    title: "Description list",
    category: "content",
    componentName: "DescriptionList",
    description: "Term and details pairs for metadata, stacked or inline.",
    sourceFiles: ["components/DescriptionList/DescriptionList.tsx", "components/DescriptionList/DescriptionList.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "divider",
    title: "Divider",
    category: "content",
    componentName: "Divider",
    description: "Horizontal or vertical separator with optional centred label.",
    sourceFiles: ["components/Divider/Divider.tsx", "components/Divider/Divider.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "content-timeline",
    title: "Content timeline",
    category: "content",
    componentName: "ContentTimeline",
    description: "Vertical event timeline for activity feeds and status updates.",
    sourceFiles: ["components/ContentTimeline/ContentTimeline.tsx", "components/ContentTimeline/ContentTimeline.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "tree-view",
    title: "Tree view",
    category: "content",
    componentName: "TreeView",
    description: "Expandable nested hierarchy for folders, menus, and org charts.",
    sourceFiles: ["components/TreeView/TreeView.tsx", "components/TreeView/TreeView.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "masonry-grid",
    title: "Masonry grid",
    category: "content",
    componentName: "MasonryGrid",
    description: "Pinterest-style column layout for cards of uneven height.",
    sourceFiles: ["components/MasonryGrid/MasonryGrid.tsx", "components/MasonryGrid/MasonryGrid.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "property-grid",
    title: "Property grid",
    category: "content",
    componentName: "PropertyGrid",
    description: "Dense key/value inspector rows with optional copy actions.",
    sourceFiles: ["components/PropertyGrid/PropertyGrid.tsx", "components/PropertyGrid/PropertyGrid.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "json-viewer",
    title: "JSON viewer",
    category: "content",
    componentName: "JsonViewer",
    description: "Read-only expandable tree for inspecting JSON payloads.",
    sourceFiles: ["components/JsonViewer/JsonViewer.tsx", "components/JsonViewer/JsonViewer.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "statistic",
    title: "Statistic",
    category: "content",
    componentName: "Statistic",
    description: "Lightweight labelled metric with optional prefix, suffix, and trend.",
    sourceFiles: ["components/Statistic/Statistic.tsx", "components/Statistic/Statistic.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "icon",
    title: "Icon",
    category: "content",
    componentName: "Icon",
    description: "Catalog Font Awesome icon with size and tone tokens.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/Icon/Icon.tsx", "components/Icon/Icon.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "icon-badge",
    title: "Icon badge",
    category: "content",
    componentName: "IconBadge",
    description: "Notification-style icon with an optional count badge for toolbars and app headers.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/IconBadge/IconBadge.tsx", "components/IconBadge/IconBadge.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "spinner",
    title: "Spinner",
    category: "content",
    componentName: "Spinner",
    description: "Inline indeterminate loading indicator.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/Spinner/Spinner.tsx", "components/Spinner/Spinner.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "clock",
    title: "Clock",
    category: "content",
    componentName: "Clock",
    description: "Analog clock with live digital time and optional date.",
    sourceFiles: ["components/Clock/Clock.tsx", "components/Clock/Clock.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "portal",
    title: "Portal",
    category: "content",
    componentName: "Portal",
    description: "Render children into a DOM host outside the React parent tree.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/Portal/Portal.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "portal-host",
    title: "Portal host",
    category: "content",
    componentName: "PortalHost",
    description: "Provides a mount target and context for Portals.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/Portal/Portal.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "visually-hidden",
    title: "Visually hidden",
    category: "content",
    componentName: "VisuallyHidden",
    description: "Hide content visually while keeping it available to assistive tech.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/VisuallyHidden/VisuallyHidden.tsx", "components/VisuallyHidden/VisuallyHidden.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "focus-trap",
    title: "Focus trap",
    category: "content",
    componentName: "FocusTrap",
    description: "Keep keyboard focus within a region while active.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/FocusTrap/FocusTrap.tsx", "components/FocusTrap/FocusTrap.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "keyboard-shortcut",
    title: "Keyboard shortcut",
    category: "content",
    componentName: "KeyboardShortcut",
    description: "Visual kbd chip(s) for documenting shortcut chords.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/KeyboardShortcut/KeyboardShortcut.tsx", "components/KeyboardShortcut/KeyboardShortcut.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "hotkey-manager",
    title: "Hotkey manager",
    category: "content",
    componentName: "HotkeyManager",
    description: "Register global keyboard shortcuts with a React context.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/HotkeyManager/HotkeyManager.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "copy-button",
    title: "Copy button",
    category: "content",
    componentName: "CopyButton",
    description: "Copy a string to the clipboard with a temporary confirmation label.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/CopyButton/CopyButton.tsx", "components/CopyButton/CopyButton.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "clipboard",
    title: "Clipboard",
    category: "content",
    componentName: "Clipboard",
    description: "Clipboard provider and hook for write/read helpers.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/Clipboard/Clipboard.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "theme-provider",
    title: "Theme provider",
    category: "content",
    componentName: "ThemeProvider",
    description: "Alias for OpusThemeProvider — sets theme context and document data-theme.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/ThemeProvider/index.ts", "components/OpusThemeProvider/OpusThemeProvider.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "theme-switcher",
    title: "Theme switcher",
    category: "content",
    componentName: "ThemeSwitcher",
    description: "Light/dark switcher control for apps and demos.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/ThemeSwitcher/ThemeSwitcher.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "resize-observer",
    title: "Resize observer",
    category: "content",
    componentName: "ResizeObserver",
    description: "Render-prop and hook wrappers around ResizeObserver.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/ResizeObserver/ResizeObserver.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "intersection-observer",
    title: "Intersection observer",
    category: "content",
    componentName: "IntersectionObserver",
    description: "Render-prop and hook wrappers around IntersectionObserver.",
    navigationGroup: "Utilities",
    sourceFiles: ["components/IntersectionObserver/IntersectionObserver.tsx"],
    usesFieldShell: false,
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    category: "content",
    componentName: "Sidebar",
    description: "Persistent navigation rail with optional header, grouped links, and layout shell.",
    navigationGroup: "Navigation",
    sourceFiles: ["components/Sidebar/Sidebar.tsx", "components/Sidebar/Sidebar.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "mega-menu",
    title: "Mega menu",
    category: "content",
    componentName: "MegaMenu",
    description: "Large navigation dropdown with grouped links, descriptions, and a featured callout.",
    navigationGroup: "Navigation",
    sourceFiles: ["components/MegaMenu/MegaMenu.tsx", "components/MegaMenu/MegaMenu.module.css"],
    usesFieldShell: false,
  },
  {
    slug: "top-navigation",
    title: "Top navigation",
    category: "content",
    componentName: "TopNavigation",
    description: "Application menu bar mixing normal dropdowns with a single MegaMenu item.",
    navigationGroup: "Navigation",
    sourceFiles: ["components/TopNavigation/TopNavigation.tsx", "components/TopNavigation/TopNavigation.module.css"],
    usesFieldShell: false,
  },
];

const controlMap = new Map<ControlSlug, ControlDefinition>();
for (const control of controls) {
  if (!controlMap.has(control.slug)) {
    controlMap.set(control.slug, control);
  }
}

export function getControlsByCategory(category: ComponentCategory): ControlDefinition[] {
  return controls
    .filter((control) => control.category === category)
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function getControlSectionsByCategory(category: ComponentCategory): {
  controls: ControlDefinition[];
  label?: string;
}[] {
  const controlsForCategory = getControlsByCategory(category);
  const ungrouped = controlsForCategory.filter((control) => !control.navigationGroup);
  const grouped = new Map<string, ControlDefinition[]>();

  for (const control of controlsForCategory) {
    if (!control.navigationGroup) {
      continue;
    }

    const items = grouped.get(control.navigationGroup) ?? [];
    items.push(control);
    grouped.set(control.navigationGroup, items);
  }

  return [
    ...(ungrouped.length ? [{ controls: ungrouped }] : []),
    ...Array.from(grouped.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([label, controls]) => ({ label, controls })),
  ];
}

export function getNavigationGroupsForCategory(category: ComponentCategory): string[] {
  return getControlSectionsByCategory(category)
    .map((section) => section.label)
    .filter((label): label is string => Boolean(label));
}

export function getNavigationGroupBySlug(category: ComponentCategory, groupSlug: string): string | null {
  return (
    getNavigationGroupsForCategory(category).find(
      (label) => label.toLowerCase().replace(/\//g, " ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") === groupSlug,
    ) ?? null
  );
}

export function getControlsForNavigationGroup(
  category: ComponentCategory,
  navigationGroup: string,
): ControlDefinition[] {
  return getControlsByCategory(category).filter((control) => control.navigationGroup === navigationGroup);
}

export function getControl(slug: string, options?: { category?: ComponentCategory }): ControlDefinition | undefined {
  if (options?.category) {
    return controls.find((control) => control.slug === slug && control.category === options.category);
  }

  return controlMap.get(slug as ControlSlug);
}

export function getAllSlugs(): ControlSlug[] {
  return [...new Set(controls.map((control) => control.slug))];
}
