import type { NotesActivityItem } from "@/components/NotesActivity";
import type { ContactDetailsContact } from "./types";

export const defaultContact: ContactDetailsContact = {
  avatarSrc: "/user-profile-emma.jpg",
  companies: [
    {
      department: "Procurement",
      employees: "1,001 – 5,000",
      industry: "Manufacturing",
      jobTitle: "Head of Procurement",
      name: "Acme Ltd",
      primary: true,
      website: "www.acme.com",
    },
    {
      department: "Advisory",
      employees: "201 – 500",
      industry: "Investment",
      jobTitle: "Procurement Advisor",
      name: "Northstar Holdings",
      website: "www.northstarholdings.com",
    },
  ],
  dateCreated: "12 Mar 2024",
  dateLastEdited: "7 May 2025",
  email: "emma.davis@acme.com",
  lastContact: "7 May 2025",
  leadStatus: "Opportunity",
  mobile: "+44 7700 900123",
  name: "Emma Winterhold-Smith",
  owner: "Carl Fearby",
  password: "OpusStaff!2025",
  phone: "+44 20 7946 0958",
  role: "Decision Maker",
  source: "LinkedIn",
  status: "Active",
  tags: ["Procurement", "ROI Focused", "Strategic"],
};

export const defaultContactNotes: NotesActivityItem[] = [
  {
    author: "Carl Fearby",
    avatarSrc: "/user-profile-carl.png",
    body: "Spoke with Emma about upcoming Q3 procurement initiatives. She’s leading the vendor review process and is particularly focused on cost savings and supplier reliability.",
    dateGroup: "7 May 2025",
    id: "contact-note-carl",
    kind: "activity",
    status: "success",
    time: "10:15",
  },
  {
    author: "Michael Brown",
    body: "Sent proposal and case study documents. Follow up next week to check on review progress and answer any questions.",
    dateGroup: "6 May 2025",
    id: "contact-note-michael",
    kind: "note",
    time: "16:30",
  },
  {
    author: "Olivia Wilson",
    body: "Initial discovery call. Emma outlined current challenges with vendor performance and budget constraints. Interested in seeing our solution in action.",
    dateGroup: "5 May 2025",
    id: "contact-note-olivia",
    kind: "activity",
    status: "success",
    time: "14:20",
  },
  {
    author: "Daniel James",
    body: "Emma confirmed the technical review team and requested security documentation before the next workshop.",
    dateGroup: "2 May 2025",
    id: "contact-note-daniel",
    kind: "activity",
    status: "default",
    time: "11:40",
  },
  {
    author: "Carl Fearby",
    avatarSrc: "/user-profile-carl.png",
    body: "Added an internal note to prepare the procurement savings model before the stakeholder presentation.",
    dateGroup: "1 May 2025",
    id: "contact-note-carl-internal",
    kind: "note",
    time: "15:05",
  },
  {
    author: "Sophia Carter",
    body: "Shared the implementation timeline and confirmed that onboarding can begin immediately after approval.",
    dateGroup: "29 April 2025",
    id: "contact-note-sophia",
    kind: "activity",
    status: "success",
    time: "09:25",
  },
  {
    author: "Michael Brown",
    body: "Emma downloaded the pricing comparison and reopened the enterprise proposal twice.",
    dateGroup: "28 April 2025",
    id: "contact-note-michael-activity",
    kind: "activity",
    status: "warning",
    time: "17:10",
  },
  {
    author: "Olivia Wilson",
    body: "Documented the current supplier renewal dates and the key decision criteria for the buying committee.",
    dateGroup: "25 April 2025",
    id: "contact-note-olivia-internal",
    kind: "note",
    time: "13:30",
  },
  {
    author: "Carl Fearby",
    avatarSrc: "/user-profile-carl.png",
    body: "Completed a follow-up call. Budget is approved in principle and legal review is the remaining dependency.",
    dateGroup: "24 April 2025",
    id: "contact-note-carl-follow-up",
    kind: "activity",
    status: "success",
    time: "10:55",
  },
  {
    author: "Daniel James",
    body: "Sent the data processing agreement and added answers to the outstanding security questionnaire.",
    dateGroup: "22 April 2025",
    id: "contact-note-daniel-documents",
    kind: "activity",
    status: "default",
    time: "16:20",
  },
];
